<?php

/* 

Please do not edit this file as it may cause errors.
Melakukan modifikasi/edit pada file ini dapat menyebabkan error atau kerusakan fungsi dari theme.

*/

// Start Functions PHP // ----------------------

// Show Admin Bar
show_admin_bar(false);

// Unregister No Need Default Widget
add_action('widgets_init', 'unregister_widgets', 11);
function unregister_widgets() {
	unregister_widget('WP_Widget_Archives');
	unregister_widget('WP_Widget_Meta');
	unregister_widget('WP_Widget_Block');
}

// Add Theme Support
if (function_exists('add_theme_support')){
	add_theme_support('menus');
	add_theme_support('post-thumbnails');
	add_image_size( 'regular', 300, 0, false );
}

// Remove Large Image Sizes
add_action( 'init', 'remove_large_image_sizes' );
function remove_large_image_sizes() {
	remove_image_size( '1536x1536' );          
	remove_image_size( '2048x2048' );  
	remove_image_size( '2560x2560' ); 
}

// Set kualitas gambar 100%
add_filter( 'jpeg_quality', 'best_quality_image' );
add_filter( 'wp_editor_set_quality', 'best_quality_image' );
function best_quality_image( $quality ) {
    return 100;
}

// Disable Widgets Block Editor
add_filter( 'use_widgets_block_editor', '__return_false' );

// Disable Gutenberg
add_filter('use_block_editor_for_post_type', 'disable_gutenberg_for_all_post_types', 10, 2);
function disable_gutenberg_for_all_post_types($use_block_editor, $post_type) {
	global $oketheme;
	if ($oketheme['gutenberg_act']) {
		return true;
	} else {
		return false;
	}
}

// Breadcrumb
function oke_crumb() {
	global $oketheme;
	if ($oketheme['crumb_act']) {
		$text['home']     = __('Beranda','oketheme');
		$text['category'] = __('Arsip "%s"','oketheme');
		$text['search']   = __('Hasil Pencarian "%s"','oketheme');
		$text['tag']      = __('Tag "%s"','oketheme');
		$text['author']   = __('Penulis "%s"','oketheme');
		$text['page']     = __('Halaman "%s"','oketheme');
		$text['cpage']    = __('Halaman Komentar "%s"','oketheme');
		$text['404']      = __('Kesalahan 404','oketheme');

		$wrap_before    = '<div class="crumbs" itemscope itemtype="http://schema.org/BreadcrumbList" data-customize-partial-id="umum" data-helper-title="Breadcrumbs" data-helper-tab="lainnya/umum">'; 
		$wrap_after     = '</div>';
		$sep            = ' &raquo; ';
		$before         = '<span class="crumbs__current">';
		$after          = '</span>';

		$show_on_home   = 0; 
		$show_home_link = 1; 
		$show_current   = 1;
		$show_last_sep  = 1; 

		global $post;
		$home_url       = home_url('/');
		$link           = '<span itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">';
		$link          .= '<a class="crumbs__link" href="%1$s" itemprop="item"><span itemprop="name">%2$s</span></a>';
		$link          .= '<meta itemprop="position" content="%3$s" />';
		$link          .= '</span>';
		$parent_id      = ( $post ) ? $post->post_parent : '';
		$home_link      = sprintf( $link, $home_url, $text['home'], 1 );

		if ( is_home() || is_front_page() ) {
			if ( $show_on_home ) echo $wrap_before . $home_link . $wrap_after;
		} else {
			$position = 0;
			echo $wrap_before;
			if ( $show_home_link ) {
				$position += 1;
				echo $home_link;
			}
			if ( is_category() ) {
				$parents = get_ancestors( get_query_var('cat'), 'category' );
				foreach ( array_reverse( $parents ) as $cat ) {
					$position += 1;
					if ( $position > 1 ) echo $sep;
					echo sprintf( $link, get_category_link( $cat ), get_cat_name( $cat ), $position );
				}
				if ( get_query_var( 'paged' ) ) {
					$position += 1;
					$cat = get_query_var('cat');
					echo $sep . sprintf( $link, get_category_link( $cat ), get_cat_name( $cat ), $position );
					echo $sep . $before . sprintf( $text['page'], get_query_var( 'paged' ) ) . $after;
				} else {
					if ( $show_current ) {
						if ( $position >= 1 ) echo $sep;
						echo $before . sprintf( $text['category'], single_cat_title( '', false ) ) . $after;
					} elseif ( $show_last_sep ) echo $sep;
				}
			} elseif ( is_search() ) {
				if ( get_query_var( 'paged' ) ) {
					$position += 1;
					if ( $show_home_link ) echo $sep;
					echo sprintf( $link, $home_url . '?s=' . get_search_query(), sprintf( $text['search'], get_search_query() ), $position );
					echo $sep . $before . sprintf( $text['page'], get_query_var( 'paged' ) ) . $after;
				} else {
					if ( $show_current ) {
						if ( $position >= 1 ) echo $sep;
						echo $before . sprintf( $text['search'], get_search_query() ) . $after;
					} elseif ( $show_last_sep ) echo $sep;
				}
			} elseif ( is_year() ) {
				if ( $show_home_link && $show_current ) echo $sep;
				if ( $show_current ) echo $before . get_the_time('Y') . $after;
				elseif ( $show_home_link && $show_last_sep ) echo $sep;
			} elseif ( is_month() ) {
				if ( $show_home_link ) echo $sep;
				$position += 1;
				echo sprintf( $link, get_year_link( get_the_time('Y') ), get_the_time('Y'), $position );
				if ( $show_current ) echo $sep . $before . get_the_time('F') . $after;
				elseif ( $show_last_sep ) echo $sep;
			} elseif ( is_day() ) {
				if ( $show_home_link ) echo $sep;
				$position += 1;
				echo sprintf( $link, get_year_link( get_the_time('Y') ), get_the_time('Y'), $position ) . $sep;
				$position += 1;
				echo sprintf( $link, get_month_link( get_the_time('Y'), get_the_time('m') ), get_the_time('F'), $position );
				if ( $show_current ) echo $sep . $before . get_the_time('d') . $after;
				elseif ( $show_last_sep ) echo $sep;
			} elseif ( is_single() && ! is_attachment() ) {
				if ( get_post_type() != 'post' ) {
					$position += 1;
					$post_type = get_post_type_object( get_post_type() );
					if ( $position > 1 ) echo $sep;
					echo sprintf( $link, get_post_type_archive_link( $post_type->name ), $post_type->labels->name, $position );
					if ( $show_current ) echo $sep . $before . get_the_title() . $after;
					elseif ( $show_last_sep ) echo $sep;
				} else {
					$cat = get_the_category(); $catID = $cat[0]->cat_ID;
					$parents = get_ancestors( $catID, 'category' );
					$parents = array_reverse( $parents );
					$parents[] = $catID;
					foreach ( $parents as $cat ) {
						$position += 1;
						if ( $position > 1 ) echo $sep;
						echo sprintf( $link, get_category_link( $cat ), get_cat_name( $cat ), $position );
					}
					if ( get_query_var( 'cpage' ) ) {
						$position += 1;
						echo $sep . sprintf( $link, get_permalink(), get_the_title(), $position );
						echo $sep . $before . sprintf( $text['cpage'], get_query_var( 'cpage' ) ) . $after;
					} else {
						if ( $show_current ) echo $sep . $before . get_the_title() . $after;
						elseif ( $show_last_sep ) echo $sep;
					}
				}
			} elseif ( is_post_type_archive() ) {
				$post_type = get_post_type_object( get_post_type() );
				if ( get_query_var( 'paged' ) ) {
					$position += 1;
					if ( $position > 1 ) echo $sep;
					echo sprintf( $link, get_post_type_archive_link( $post_type->name ), $post_type->label, $position );
					echo $sep . $before . sprintf( $text['page'], get_query_var( 'paged' ) ) . $after;
				} else {
					if ( $show_home_link && $show_current ) echo $sep;
					if ( $show_current ) echo $before . $post_type->label . $after;
					elseif ( $show_home_link && $show_last_sep ) echo $sep;
				}
			} elseif ( is_attachment() ) {
				$parent = get_post( $parent_id );
				$cat = get_the_category( $parent->ID ); 
				$catID = @$cat[0]->cat_ID;
				$parents = get_ancestors( $catID, 'category' );
				$parents = array_reverse( $parents );
				$parents[] = $catID;
				foreach ( $parents as $cat ) {
					$position += 1;
					if ( $position > 1 ) echo $sep;
					echo sprintf( $link, get_category_link( $cat ), get_cat_name( $cat ), $position );
				}
				$position += 1;
				echo $sep . sprintf( $link, get_permalink( $parent ), $parent->post_title, $position );
				if ( $show_current ) echo $sep . $before . get_the_title() . $after;
				elseif ( $show_last_sep ) echo $sep;
			} elseif ( is_page() && ! $parent_id ) {
				if ( $show_home_link && $show_current ) echo $sep;
				if ( $show_current ) echo $before . get_the_title() . $after;
				elseif ( $show_home_link && $show_last_sep ) echo $sep;
			} elseif ( is_page() && $parent_id ) {
				$parents = get_post_ancestors( get_the_ID() );
				foreach ( array_reverse( $parents ) as $pageID ) {
					$position += 1;
					if ( $position > 1 ) echo $sep;
					echo sprintf( $link, get_page_link( $pageID ), get_the_title( $pageID ), $position );
				}
				if ( $show_current ) echo $sep . $before . get_the_title() . $after;
				elseif ( $show_last_sep ) echo $sep;
			} elseif ( is_tag() ) {
				if ( get_query_var( 'paged' ) ) {
					$position += 1;
					$tagID = get_query_var( 'tag_id' );
					echo $sep . sprintf( $link, get_tag_link( $tagID ), single_tag_title( '', false ), $position );
					echo $sep . $before . sprintf( $text['page'], get_query_var( 'paged' ) ) . $after;
				} else {
					if ( $show_home_link && $show_current ) echo $sep;
					if ( $show_current ) echo $before . sprintf( $text['tag'], single_tag_title( '', false ) ) . $after;
					elseif ( $show_home_link && $show_last_sep ) echo $sep;
				}
			} elseif ( is_author() ) {
				$author = get_userdata( get_query_var( 'author' ) );
				if ( get_query_var( 'paged' ) ) {
					$position += 1;
					echo $sep . sprintf( $link, get_author_posts_url( $author->ID ), sprintf( $text['author'], $author->display_name ), $position );
					echo $sep . $before . sprintf( $text['page'], get_query_var( 'paged' ) ) . $after;
				} else {
					if ( $show_home_link && $show_current ) echo $sep;
					if ( $show_current ) echo $before . sprintf( $text['author'], $author->display_name ) . $after;
					elseif ( $show_home_link && $show_last_sep ) echo $sep;
				}
			} elseif ( is_404() ) {
				if ( $show_home_link && $show_current ) echo $sep;
				if ( $show_current ) echo $before . $text['404'] . $after;
				elseif ( $show_last_sep ) echo $sep;
			} elseif ( has_post_format() && ! is_singular() ) {
				if ( $show_home_link && $show_current ) echo $sep;
				echo get_post_format_string( get_post_format() );
			}
			echo $wrap_after;
		}
	}
}

// Pagination
function oke_pagination() {
    global $wp_query;
	if ($wp_query->max_num_pages > 1) {
		$big = 999999999;
		echo '<div class="pagination">';
		echo paginate_links(array(
			'base' 		=> str_replace($big, '%#%', get_pagenum_link($big)),
			'format' 	=> '?paged=%#%',
			'current'	=> max(1, get_query_var('paged')),
			'total' 	=> $wp_query->max_num_pages,
			'prev_text' => '&laquo;',
			'next_text' => '&raquo;'
		));
		echo '</div>';
	}
}

// SEO Custom Title
add_filter( 'wp_title', 'seo_wp_title', 10, 2 );
function seo_wp_title( $title, $sep ) {
	global $paged, $page;
	if ( is_feed() )
		return $title;
	$title		.= get_bloginfo( 'name', 'display' );
	$site_desc	= get_bloginfo( 'description', 'display' );
	if ( $site_desc && ( is_home() || is_front_page() ) )
		$title = "$title $sep $site_desc";
	if ( $paged >= 2 || $page >= 2 )
		$title = "$title $sep " . sprintf( __( 'Page %s', '' ), max( $paged, $page ) );
	return $title;
}

// Disable Emojis
add_action( 'init', 'disable_emojis' );
function disable_emojis() {
    remove_action( 'wp_head', 'print_emoji_detection_script', 7 );
    remove_action( 'admin_print_scripts', 'print_emoji_detection_script' );
    remove_action( 'wp_print_styles', 'print_emoji_styles' );
    remove_action( 'admin_print_styles', 'print_emoji_styles' );
}

// Hide Dashboard Warning
add_action('admin_head', 'hide_dashwarning');
function hide_dashwarning() {
	echo '<style>#dashboard_php_nag,#dashboard_site_health {display:none}</style>';
}

// Enqueue Oketheme Style & Scripts
add_action('wp_enqueue_scripts', 'oketheme_scripts', 10); 
function oketheme_scripts() {
	global $oketheme;  
	wp_enqueue_script('jquery');

	// Font Awesome
	wp_enqueue_style( 'fa5', 'https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/all.min.css?ver=5.15.5', array(), '5.15.5', 'all' );

	// Splide
	wp_enqueue_script( 'splide', get_template_directory_uri() . '/libs/splide/splide.min.js', '', '4.1.3', true );
	wp_enqueue_style('splide', get_template_directory_uri() . '/libs/splide/splide.min.css', '', '4.1.3', 'screen');

	// LightSlider
	if(is_single()) {
		wp_enqueue_script( 'lightslider', get_template_directory_uri() . '/libs/lightslider/lightslider.js', '', '', true );
		wp_enqueue_style('lightslider', get_template_directory_uri() . '/libs/lightslider/lightslider.css', '', '', 'screen');
		wp_add_inline_script('lightslider','
			jQuery(document).ready(function($) {
				$("#post-galeri").lightSlider({
					gallery: true,
					item: 1,
					thumbItem: 5,
					thumbMargin: 10,
					slideMargin: 0,
					loop: true,
					adaptiveHeight: true,
					mode: "fade",
					onSliderLoad: function() {
						$("#post-galeri").removeClass("cS-hidden");
					}
				});
			});
		');
	}

	// Oketabs
	if(is_home()) {
		wp_enqueue_script( 'oketabs', get_template_directory_uri() . '/libs/oketabs/oketabs.js', '', '', true );
		wp_enqueue_style('oketabs', get_template_directory_uri() . '/libs/oketabs/oketabs.css', '', '', 'screen');
	}

	// Material Icons
	wp_enqueue_style('material', get_template_directory_uri() . '/libs/material/material.css', '', '', 'screen');

	// IcoFont
	wp_enqueue_style('icofont', get_template_directory_uri() . '/libs/icofont/icofont.min.css', '', '', 'screen');

	// Fancybox
	if($oketheme['popup_act']) {
		wp_enqueue_script( 'fancybox', get_template_directory_uri() . '/libs/fancybox/fancybox.js', '', '', true );
		wp_enqueue_style('fancybox', get_template_directory_uri() . '/libs/fancybox/fancybox.css', '', '', 'screen');
		wp_add_inline_script('fancybox', '
			jQuery(document).ready(function($) {
				$(".autopop").fancybox({
					autoSize: !0,
					touch: false,
				}).trigger("click");
			});
		');
	}

	// Gutenberg
	if(!$oketheme['gutenberg_act']) {	
		wp_dequeue_style('wp-block-library'); // Untuk frontend
		wp_dequeue_style('wp-block-library-theme'); // Untuk tema tambahan Gutenberg
	}
	
	// Helper
    if (current_user_can('manage_options') && !wp_is_mobile()) {
		wp_enqueue_style('helper', get_template_directory_uri() . '/inc/helper/helper.css', array('theme'), '1.0', 'all');
        wp_enqueue_script('helper', get_template_directory_uri() . '/inc/helper/helper.js', array('theme'), '1.0', true);
    }

	// Oketheme
	wp_enqueue_style('theme', get_template_directory_uri() . '/assets/css/theme.css', '', '1.0', 'all');
	wp_enqueue_script( 'theme', get_template_directory_uri() . '/assets/js/theme.js', '', '1.0', true );
}

// Enqueue Admin Oketheme Style & Scripts
add_action('admin_enqueue_scripts', 'oketheme_admin_scripts');
function oketheme_admin_scripts() {
	wp_enqueue_style('admin', get_template_directory_uri() . '/assets/css/admin.css', '', '1.0', 'all');
	wp_enqueue_script( 'admin', get_template_directory_uri() . '/assets/js/admin.js', '', '1.0', true );
}

// ------------------------- End Setting ------------------------- //

// Configuration
function config_data() {
    return array(
        'opt_safe_mode'     => false,
        'opt_post_max_show' => 100,
        'opt_cat_max_show'  => 100,
        'opt_tag_max_show'  => 100,
        'opt_custom_mode'   => false,
        'opt_custom_fields' => array(),
        'php_default'       => '7.4',
        // 'php_required'      => array('7.2', '7.3', '7.4'),
        'php_required'      => array('8.2'),
    );
}

// Checking PHP & IonCube Loader
$php_version    = PHP_VERSION;
$required_php   = config_data()['php_required'];
$ioncube_loaded = function_exists('ioncube_loader_version');
$compatible_php = false;

// Jika php_required kosong → fallback minimal php_default
if (empty($required_php)) {
    $compatible_php = version_compare($php_version, config_data()['php_default'], '>=');
} else {
    foreach ($required_php as $ver) {
        if (version_compare($php_version, $ver, '>=') && version_compare($php_version, (float)$ver + 0.1, '<')) {
            $compatible_php = true;
            break;
        }
    }
}

// Jika tidak memenuhi syarat
if ( ! $compatible_php || ! $ioncube_loaded ) {

    if ( is_admin() && current_user_can('manage_options') ) {
        add_action('admin_notices', function() use ($php_version, $required_php, $ioncube_loaded, $compatible_php) {
            $required_text = !empty($required_php) ? implode('.x, ', $required_php) . '.x' : '>= ' . config_data()['php_default'];

            echo '<div class="notice notice-error"><p><strong style="color:red">Server Requirements Warning</strong><br>'
                . wp_get_theme()->Name . ' Theme belum dapat digunakan karena memerlukan <b style="color:green">PHP ' . $required_text . '</b> dan ekstensi <b style="color:green">IonCube Loader</b>.</p><p>';

            if ( ! $compatible_php ) {
                echo '<span class="dashicons dashicons-no-alt" style="color:red"></span> Server Anda menggunakan PHP ' . $php_version . '<br>';
            } else {
                echo '<span class="dashicons dashicons-yes" style="color:green"></span> Server Anda sudah menggunakan PHP ' . $php_version . '<br>';
                if ( ! $ioncube_loaded ) {
                echo '<span class="dashicons dashicons-no-alt" style="color:red"></span> Ekstensi IonCube Loader belum diaktifkan<br>';
            }
            }

            echo '</p><p>Silakan lakukan perubahan melalui control panel hosting/server Anda. Anda juga dapat menghubungi penyedia hosting untuk membantu melakukan perubahan tersebut.</p></div>';
        });
    }

    if ( ! is_admin() ) {
        add_action('template_redirect', function() {
            echo '<link rel="preconnect" href="https://fonts.gstatic.com">';
            echo '<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">';
            echo '
            <div style="text-align:center;max-width:700px;margin:40px auto;font-family:Roboto;font-size: 16px;">
                <h1 style="margin:0;font-weight:700">WEBSITE BELUM SIAP!</h1>
                <p><img src="'. get_template_directory_uri() .'/inc/codestar/assets/images/maintenance.gif"></p>
                <p>Maaf, website kami belum siap saat ini. Silahkan kunjungi lagi nanti, terima kasih :-)</p>
                <p style="font-size:12px">Jika Anda adalah admin website ini, silahkan login <a href="'. get_bloginfo('url') .'/wp-admin/themes.php"><u>disini</u></a></p>
            </div>';
            exit;
        });
    }

} else {
    ob_start();
    
    // Semua syarat terpenuhi, load required file
    require_once( dirname( __FILE__ ) . '/core/en/locked.php');
    require_once( dirname( __FILE__ ) . '/core/configs.php');
    require_once( dirname( __FILE__ ) . '/core/parts.php');

    if (isset($_GET['activated']) && is_admin()) {
        wp_safe_redirect(admin_url('admin.php?page=verifikasi-oketheme'));
        exit;
    }
}
