<?php 

/* 

Please do not edit this file as it may cause errors.
Melakukan modifikasi/edit pada file ini dapat menyebabkan error atau kerusakan fungsi dari theme.

*/

// Force Change Default Options WordPress
add_action('after_switch_theme', 'config_wp_options');
function config_wp_options() {
	update_option('posts_per_page', 10);
	update_option('show_on_front', 'posts');
	update_option('comment_order', 'desc');
	update_option('thumbnail_size_w', 150);
	update_option('thumbnail_size_h', 150);
	update_option('medium_size_w', 400);
	update_option('medium_size_h', 400);
	if (get_option( 'permalink_structure' ) == '') {
		update_option('permalink_structure', '/%postname%.html');
	}
}

// Register Sidebar
if (function_exists('register_sidebar')) {	
	register_sidebar(array(
        'name' => __('Sidebar', 'oketheme'),
        'description' => __('Tarik widget disini untuk menampilkan di Sidebar', 'oketheme'),
        'id' => 'sidebar',
        'before_widget' => '<div class="box-content widgets" data-customize-partial-id="sidebar-widgets-sidebar" data-helper-title="Widgets Area: Sidebar" data-helper-link="'.admin_url('widgets.php').'">',
        'after_widget' => '</div>',
        'before_title' => '<div class="_title"><h4>',
        'after_title' => '</h4></div>'
    ));
    register_sidebar(array(
        'name' => __('Footer: Kiri', 'oketheme'),
        'description' => __('Tarik widget disini untuk menampilkan di Footer Area (Kiri)', 'oketheme'),
        'id' => 'footer-left',
        'before_widget' => '<div class="widgets" data-customize-partial-id="sidebar-widgets-footer-left" data-helper-title="Widgets Area: Footer Kiri" data-helper-link="'.admin_url('widgets.php').'">',
        'after_widget' => '</div>',
        'before_title' => '<h4>',
        'after_title' => '</h4>'
    ));
    register_sidebar(array(
        'name' => __('Footer: Tengah', 'oketheme'),
        'description' => __('Tarik widget disini untuk menampilkan di Footer Area (Tengah)', 'oketheme'),
        'id' => 'footer-mid',
        'before_widget' => '<div class="widgets" data-customize-partial-id="sidebar-widgets-footer-mid" data-helper-title="Widgets Area: Footer Tengah" data-helper-link="'.admin_url('widgets.php').'">',
        'after_widget' => '</div>',
        'before_title' => '<h4>',
        'after_title' => '</h4>'
    ));
	register_sidebar(array(
        'name' => __('Footer: Kanan', 'oketheme'),
        'description' => __('Tarik widget disini untuk menampilkan di Footer Area (Kanan)', 'oketheme'),
        'id' => 'footer-right',
        'before_widget' => '<div class="widgets" data-customize-partial-id="sidebar-widgets-footer-right" data-helper-title="Widgets Area: Footer Kanan" data-helper-link="'.admin_url('widgets.php').'">',
        'after_widget' => '</div>',
        'before_title' => '<h4>',
        'after_title' => '</h4>'
    ));
}

// Hour Post Time
function the_post_time() {
    $post_time = get_the_time('U'); // timestamp posting
    $current_time = current_time('timestamp');
    $time_diff = $current_time - $post_time;

    if ($time_diff < DAY_IN_SECONDS) {
        $hours_ago = floor($time_diff / HOUR_IN_SECONDS);
        if ($hours_ago == 0) {
            $minutes_ago = floor($time_diff / MINUTE_IN_SECONDS);
            echo $minutes_ago . ' ' . __('menit yang lalu', 'oketheme');
        } else {
            echo $hours_ago . ' ' . __('jam yang lalu', 'oketheme');
        }
    } else {
        // Paksa ambil nama hari & bulan dalam English
        $english_day   = gmdate('D', $post_time); // ex: Sun, Mon, Tue
        $english_month = gmdate('M', $post_time); // ex: Jan, Feb, Mar

        $days = array(
            'Sun' => __('Minggu', 'oketheme'),
            'Mon' => __('Senin', 'oketheme'),
            'Tue' => __('Selasa', 'oketheme'),
            'Wed' => __('Rabu', 'oketheme'),
            'Thu' => __('Kamis', 'oketheme'),
            'Fri' => __('Jumat', 'oketheme'),
            'Sat' => __('Sabtu', 'oketheme'),
        );

        $months = array(
            'Jan' => __('Jan', 'oketheme'),
            'Feb' => __('Feb', 'oketheme'),
            'Mar' => __('Mar', 'oketheme'),
            'Apr' => __('Apr', 'oketheme'),
            'May' => __('Mei', 'oketheme'),
            'Jun' => __('Jun', 'oketheme'),
            'Jul' => __('Jul', 'oketheme'),
            'Aug' => __('Agt', 'oketheme'),
            'Sep' => __('Sep', 'oketheme'),
            'Oct' => __('Okt', 'oketheme'),
            'Nov' => __('Nov', 'oketheme'),
            'Dec' => __('Des', 'oketheme'),
        );

        $day   = isset($days[$english_day]) ? $days[$english_day] : $english_day;
        $month = isset($months[$english_month]) ? $months[$english_month] : $english_month;

        // format akhir: "Rabu, 6 Nov 2025"
        echo $day . ', ' . gmdate('j', $post_time) . ' ' . $month . ' ' . gmdate('Y', $post_time);
    }
}

// Current Day (prepare for flash blog off)
function the_current_day() {
    $hari = array(
        'Sunday'    => 'Minggu',
        'Monday'    => 'Senin',
        'Tuesday'   => 'Selasa',
        'Wednesday' => 'Rabu',
        'Thursday'  => 'Kamis',
        'Friday'    => 'Jumat',
        'Saturday'  => 'Sabtu'
    );

    $bulan = array(
        'Jan' => 'Jan',
        'Feb' => 'Feb',
        'Mar' => 'Mar',
        'Apr' => 'Apr',
        'May' => 'Mei',
        'Jun' => 'Jun',
        'Jul' => 'Jul',
        'Aug' => 'Agu',
        'Sep' => 'Sep',
        'Oct' => 'Okt',
        'Nov' => 'Nov',
        'Dec' => 'Des'
    );

    // Menggunakan current_time('timestamp') agar sesuai dengan zona waktu WordPress
    $timestamp = current_time('timestamp');

    // Ambil nama hari dalam bahasa Inggris lalu konversi ke bahasa Indonesia
    $hari_ini = $hari[date('l', $timestamp)];

    // Ambil tanggal dan bulan dalam format yang sesuai
    $tanggal = date('j', $timestamp); // Tanggal tanpa leading zero
    $bulan_ini = $bulan[date('M', $timestamp)];
    $tahun = date('Y', $timestamp);

    echo "$hari_ini, $tanggal $bulan_ini $tahun";
}

// Popular Tags
function the_popular_tags($period = 'all') {
    global $wpdb;
    $limit  = 15;
    $tags   = [];
    $today  = current_time('mysql');

    // Daftar periode yang tersedia
    $periods = [
        '7d'  => 7 * DAY_IN_SECONDS,
        '1m'  => 30 * DAY_IN_SECONDS,
        '3m'  => 90 * DAY_IN_SECONDS,
        '1y'  => 365 * DAY_IN_SECONDS,
        'all' => 0, // Sepanjang masa
    ];

    // Pastikan periode yang dipilih valid
    if (!isset($periods[$period])) {
        $period = '1m'; // Gunakan default 1 bulan jika periode tidak valid
    }

    // Jika bukan 'all', hitung tanggal mulai
    $start_date = $periods[$period] ? date('Y-m-d H:i:s', strtotime($today) - $periods[$period]) : null;

    // Query berdasarkan periode
    if ($start_date) {
        $query = $wpdb->prepare("
            SELECT terms.term_id, terms.name, terms.slug, COUNT(tr.object_id) AS tag_count
            FROM {$wpdb->term_taxonomy} AS tt
            INNER JOIN {$wpdb->terms} AS terms ON tt.term_id = terms.term_id
            INNER JOIN {$wpdb->term_relationships} AS tr ON tt.term_taxonomy_id = tr.term_taxonomy_id
            INNER JOIN {$wpdb->posts} AS posts ON tr.object_id = posts.ID
            WHERE tt.taxonomy = 'post_tag' 
                AND posts.post_status = 'publish'
                AND posts.post_date >= %s
            GROUP BY terms.term_id
            ORDER BY tag_count DESC
            LIMIT {$limit}
        ", $start_date);
    } else {
        // Query untuk sepanjang masa (tanpa filter tanggal)
        $query = "
            SELECT terms.term_id, terms.name, terms.slug, COUNT(tr.object_id) AS tag_count
            FROM {$wpdb->term_taxonomy} AS tt
            INNER JOIN {$wpdb->terms} AS terms ON tt.term_id = terms.term_id
            INNER JOIN {$wpdb->term_relationships} AS tr ON tt.term_taxonomy_id = tr.term_taxonomy_id
            WHERE tt.taxonomy = 'post_tag'
            GROUP BY terms.term_id
            ORDER BY tag_count DESC
            LIMIT {$limit}
        ";
    }

    $tags = $wpdb->get_results($query);

    // Output tags dalam format #hashtag link
    if (!empty($tags)) {
        echo '<div class="_content hscroll">';
        foreach ($tags as $tag) {
            $tag_link = get_tag_link($tag->term_id);
            echo '<a href="' . esc_url($tag_link) . '">#' . esc_html($tag->name) . '</a> ';
        }
        echo '</div>';
    } else {
        echo __('Maaf, tidak ditemukan tags pada periode waktu yang ditentukan.', 'oketheme');
    }
}

// Gallery Single
function the_gallery() {
    global $oketheme;
    if (!empty(rwmb_meta($oketheme['post_meta_gallery']))) {
        $image_data = maybe_unserialize(rwmb_meta($oketheme['post_meta_gallery']));
        $image_data = array_values($image_data);

        if(count($image_data) == 1) { ?>
            <div class="ofc">
                <img src="<?php echo img_url(array_key_first($gambar), 'large');?>" alt="<?php the_title(); ?>">
            </div>
        <?php } else {
            // Paginated Gallery
            if(rwmb_meta($oketheme['post_meta_gallery_type']) == 'page') {

                // Ambil bagian saat ini
                $current_part = isset($_GET['image']) ? intval($_GET['image']) - 1 : 0;
                $total_parts = count($image_data);

                // Validasi indeks array
                if ($current_part < 0 || $current_part >= $total_parts) {
                    $current_part = 0; // fallback ke bagian pertama jika indeks tidak valid
                }

                // Ambil data gambar berdasarkan indeks
                $image_info = $image_data[$current_part];
                $image_url = $image_info['full_url'] ?? ''; // URL gambar ukuran penuh
                $image_caption = $image_info['caption'] ?? '';

                // Tombol Sebelumnya
                $prev_class = $current_part > 0 ? '_prev' : '_prev disabled';
                $prev_aria = $current_part > 0 ? 'false' : 'true';
                $prev_href = $current_part > 0 ? add_query_arg('image', $current_part) . '#gallery' : '#';

                // Tombol Selanjutnya
                $next_class = $current_part < $total_parts - 1 ? '_next' : '_next disabled';
                $next_aria = $current_part < $total_parts - 1 ? 'false' : 'true';
                $next_href = $current_part < $total_parts - 1 ? add_query_arg('image', $current_part + 2) . '#gallery' : '#';

                echo  '<div id="gallery" class="_gallery flexcon column gap-10 nm">';
                
                    // Tampilkan gambar besar
                    echo '<div class="_image">';
                        echo '<img src="' . esc_url($image_url) . '" alt="' . esc_attr($image_caption) . '">';
                        // Navigasi prev/next di gambar besar
                        echo '<div class="_nav">';
                            if ($current_part > 0) {
                                echo '<a href="' . add_query_arg('image', $current_part) . '#gallery" class="_prev"><i class="m-icon">chevron_left</i></a>';
                            }
                            if ($current_part < $total_parts - 1) {
                                echo '<a href="' . add_query_arg('image', $current_part + 2) . '#gallery" class="_next"><i class="m-icon">chevron_right</i></a>';
                            }
                        echo '</div>';
                    echo '</div>';

                    if (!empty($image_caption)) {
                        echo '<p class="_featured-caption">' . esc_html($image_caption) . '</p>';
                    }

                    // Navigasi prev/next
                    echo '<div class="_navigation">';
                        // Tombol Sebelumnya
                        echo '<a href="' . esc_url($prev_href) . '" class="' . esc_attr($prev_class) . '" aria-disabled="' . esc_attr($prev_aria) . '">';
                        echo '<i class="m-icon">chevron_left</i> ' . __('Sebelumnya', 'oketheme') . '</a>';
                        // Halaman saat ini
                        echo '<span class="_page">' . ($current_part + 1) . '/' . $total_parts . '</span>';
                        // Tombol Selanjutnya
                        echo '<a href="' . esc_url($next_href) . '" class="' . esc_attr($next_class) . '" aria-disabled="' . esc_attr($next_aria) . '">';
                        echo __('Selanjutnya', 'oketheme') . ' <i class="m-icon">chevron_right</i></a>';
                    echo '</div>';

                    // Navigasi thumbnail
                    echo '<div class="_thumbnail hscroll">';
                        foreach ($image_data as $index => $image) {
                            $thumb_url = $image['sizes']['thumbnail']['url'] ?? '';
                            $thumb_index = $index + 1; // Sesuaikan indeks dengan mulai dari 1
                            $thumb_class = ($index === $current_part) ? 'current' : '';
                            echo '<a href="' . add_query_arg('image', $thumb_index) . '#gallery" class="' . esc_attr($thumb_class) . '">';
                            echo '<img src="' . esc_url($thumb_url) . '" alt="' . esc_attr($image['caption'] ?? '') . '">';
                            echo '</a>';
                        }
                    echo '</div>';

                echo '</div>';
            } 
            
            // Carousel Gallery
            else { 
                echo "<div id='post-galeri'>";
                foreach($image_data as $img):
                    $urlbesar	= img_url($img['ID'], 'large');	
                    $urlkecil	= img_url($img['ID'], 'thumbnail');
                    echo "<div data-thumb='{$urlkecil}'><img src='{$urlbesar}'/></div>";
                endforeach;
                echo "</div>"; 
            } 
        }
    }
}

// Add Page Break
add_filter( 'mce_buttons', 'add_page_break_button' );
function add_page_break_button( $buttons ) {
    // Menambahkan tombol 'Page Break' ke toolbar
    array_push( $buttons, 'wp_page' );
    return $buttons;
}

// Get Image Size
function get_wh_img($img_url) {
    // Inisialisasi cURL
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $img_url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_BINARYTRANSFER, 1);

    // Mendapatkan konten gambar
    $imageData = curl_exec($ch);
    curl_close($ch);

    // Mendapatkan ukuran gambar
    if ($imageData !== false) {
        $imageSize = getimagesizefromstring($imageData);
        if ($imageSize !== false) {
            $width = $imageSize[0];
            $height = $imageSize[1];
            return 'width="' . $width . '" height="' . $height . '"';
        }
    }
}

// Get Image URL by ID Attachment
function img_url($id, $size = 'full') {
    if (empty($id)) {
        return '';
    }
    $image_url = wp_get_attachment_image_src($id, $size);
    if (is_array($image_url) && !empty($image_url[0])) {
        return $image_url[0];
    } else {
        return '';
    }
}

// Menambahkan ALT text ke gambar
add_filter('post_thumbnail_html', function($html, $post_id, $post_thumbnail_id, $size, $attr) {
    global $oketheme;
    if (!$oketheme['auto_alt_act']) return $html;

    $post_title = esc_attr(get_the_title($post_id));
    $current_alt = get_post_meta($post_thumbnail_id, '_wp_attachment_image_alt', true);

    // Jika ALT sudah ada dan tidak kosong, biarkan
    if (!empty($current_alt)) return $html;

    // Tambahkan atau ganti ALT jika kosong
    if (preg_match('/alt\s*=\s*""/', $html)) {
        $html = preg_replace('/alt\s*=\s*""/', 'alt="' . $post_title . '"', $html);
    } elseif (strpos($html, 'alt=') === false) {
        $html = preg_replace('/<img(.*?)\/?>/i', '<img$1 alt="' . $post_title . '" />', $html);
    }

    return $html;
}, 10, 5);

// Menampilkan Caption Thumbnail
function the_caption_thumbnail() {
    $image_post = get_post(get_post_thumbnail_id());
    if (!empty($image_post->post_excerpt)) {
        echo '<p class="_featured-caption">' . esc_html($image_post->post_excerpt) . '</p>';
    }
}

// Get Youtube Video ID
function get_yID($video_url) {
    // Jika URL menggunakan format youtu.be
    if (strpos($video_url, 'youtu.be') !== false) {
        $id = substr($video_url, strrpos($video_url, '/') + 1);
    } 
    // Jika URL menggunakan format youtube.com/watch?v=
    elseif (strpos($video_url, 'youtube.com') !== false && strpos($video_url, 'v=') !== false) {
        $queryString = parse_url($video_url, PHP_URL_QUERY);
        parse_str($queryString, $params);
        $id = isset($params['v']) ? $params['v'] : '';
    } 
    // Jika URL tidak valid
    else {
        $id = '';
    }
    return $id;
}

// Loop Template
function loop($size = 'medium', $class = '') {
    global $oketheme;?>
    <div class="loop <?php echo esc_attr($class); ?>">
        <a href="<?php the_permalink(); ?>" class="_pigura ofc" aria-label="<?php the_title(); ?>">
            <?php // Featured Image
            if ( has_post_thumbnail()) { 
                the_post_thumbnail($size);
            } else {?>
                <img src="<?php echo get_template_directory_uri(); ?>/assets/img/<?=$size;?>.jpg" alt="<?php the_title(); ?>">
            <?php }
            
            // Video
            if (rwmb_get_value($oketheme['post_meta_video']) != '') {
                
                // Video Duration
                if (rwmb_meta($oketheme['post_meta_video_duration'])) { ?>
                    <span class="_duration"><?php echo rwmb_meta($oketheme['post_meta_video_duration']); ?></span>
                <?php } ?>

                <!-- Play Button -->
                <svg class="play-thumb" viewBox="0 0 28 28">
                    <title>Play Button</title><path d="M11,19V9l8,5L11,19z"></path><path class="transparent" d="M14,2c6.62,0,12,5.38,12,12s-5.38,12-12,12S2,20.62,2,14S7.38,2,14,2 M14,0C6.27,0,0,6.27,0,14 c0,7.73,6.27,14,14,14s14-6.27,14-14C28,6.27,21.73,0,14,0L14,0z"></path>
                </svg>

                <!-- Video Thumbnail -->
                <?php if (!empty(rwmb_meta($oketheme['post_meta_video_thumbnail']))) { ?>
                    <span class="video-thumb ofc">
                        <?php echo '<img src="'.img_url(array_key_first(rwmb_meta($oketheme['post_meta_video_thumbnail']))).'">'; ?>
                    </span>
                <?php }
            } 

            // Foto
            if (!empty(rwmb_meta($oketheme['post_meta_gallery']))) { ?>
                <!-- Jumlah Foto -->
                <span class="img-thumb flexcon justify-center align-center gap-5">
                    <i class="m-icon">photo_camera</i> <?php echo count(rwmb_meta($oketheme['post_meta_gallery']));?>
                </span>
            <?php } ?>
        </a>

        <div class="_content flexcon column nm gap-10">
            <?php if($class == '_epaper') { ?>
                <h3 class="elipsis clamp2"><a href="<?php the_permalink(); ?>" title="<?php the_title(); ?>"><?php the_title(); ?></a></h3>
                <span class="_price color2"><?php echo rwmb_meta($oketheme['epaper_meta_price'])?:__('Gratis','oketheme'); ?></span>
            <?php } else { ?>
                <div class="_category">
                    <?php the_category(' '); ?>
                </div>
                <h3 class="elipsis clamp2"><a href="<?php the_permalink(); ?>" title="<?php the_title(); ?>"><?php the_title(); ?></a></h3>
                <ul class="_detail flexcon wrap col-gap-15 row-gap-5 nolist">
                    <?php if(!empty($oketheme['loop_detail'])) {
                        if (in_array("date", $oketheme['loop_detail'])) { ?>
                            <li class="_date"><i class="m-icon">calendar_month</i> <?php the_post_time(); ?></li>
                        <?php } if (in_array("author", $oketheme['loop_detail'])) { ?>
                            <li class="_author"><i class="m-icon">account_circle</i> <?=rwmb_meta($oketheme['post_meta_writer'])?: get_the_author(); ?></li>
                        <?php } if (in_array("views", $oketheme['loop_detail'])) { ?>
                            <li class="_views"><i class="m-icon">visibility</i> <?php echo getPostViews(get_the_ID()); ?></li>
                        <?php } 
                    }?>
                    <li class="_comments"><span class="_count"> <?php echo get_comments_number().'</span>'.__('Komentar', 'oketheme'); ?></li>
                </ul>
            <?php } ?>
            <div class="elipsis clamp3 _excerpt"><?php the_excerpt(); ?></div>
        </div>
    </div>
    <?php 
}

// Enable Threaded Comments
add_action('get_header', 'enable_threaded_comments');
function enable_threaded_comments(){
	if (!is_admin()) {
        if (is_singular() AND comments_open() AND (get_option('thread_comments') == 1)) {
            wp_enqueue_script('comment-reply');
        }
    }
}

// Komentar Callback
function komentar($comment, $args, $depth) {
	if ( 'div' === $args['style'] ) {
		$tag       = 'div';
		$add_below = 'comment';
	} else {
		$tag       = 'li';
		$add_below = 'div-comment';
	}?>
	<<?php echo $tag; ?> <?php comment_class( empty( $args['has_children'] ) ? '' : 'parent' ); ?> id="comment-<?php comment_ID() ?>">
    <div id="div-comment-<?php comment_ID(); ?>" class="komentar">
		<?php // Avatar
		echo get_avatar($comment,$size='60'); 
		// Author Name
		echo '<strong>'.$comment->comment_author.'</strong>';
		// Comment Text
		comment_text();
		// Reply
		comment_reply_link( array_merge( $args, array(
			'reply_text' => __('Balas','oketheme'),
			'add_below'  => 'div-comment',
			'depth'      => $depth,
			'max_depth'  => $args['max_depth'],
			'before'     => '<span style="margin-right:10px;font-size:90%">',
			'after'      => '</span>'
		) ) );
		// Edit
		edit_comment_link( __( 'Edit' ), '<span style="margin-right:10px;font-size:90%">', '</span>' );
		// Date
		echo '<a href="'.htmlspecialchars( get_comment_link( $comment->comment_ID )).'">';
			printf( __('<span class="medium">%1$s %2$s</span>'), get_comment_date('j F Y'),  get_comment_time() );
		echo '</a>';
		// Moderation Info
		if ( $comment->comment_approved == '0' ) {
			echo '<p class="notice nm-bottom">'.__('Terima kasih, komentar Anda akan melewati proses moderasi untuk dapat ditampilkan.','oketheme').'</p>'; 
		}?> 
	</div>
<?php
}

// Add Index Page
add_action('after_switch_theme', 'add_index_page');
function add_index_page() {
    $page_slug = 'index-berita';
    $page_title = 'Index Berita';
    $page_template = 'temp-index.php';

    // Cek apakah halaman sudah ada
    $page_check = get_page_by_path($page_slug);
    
    if (!$page_check) {
        // Buat halaman baru jika belum ada
        $new_page_id = wp_insert_post(array(
            'post_type'      => 'page',
            'post_title'     => $page_title,
            'post_content'   => '',
            'post_status'    => 'publish',
            'post_author'    => 1,
            'comment_status' => 'closed',
        ));

        // Set template halaman
        if ($new_page_id) {
            update_post_meta($new_page_id, '_wp_page_template', $page_template);
        }
    }
}

// Query Variable WordPress
add_filter('query_vars', function($vars) {
    $vars[] = 'pdf_url';
    return $vars;
});

// Rewrite Rule
add_action('init', function() {
    global $oketheme;
    global $pagenow;

    // PDF Rewrite Rule
    add_rewrite_rule('^proxie_pdf?$', 'index.php?pdf_url=1', 'top');

    // Custom Login Rewrite Rule
    if(!empty($oketheme['custom_login']['act']) && $oketheme['custom_login']['slug'] != '') {
        add_rewrite_rule('^' . $oketheme['custom_login']['slug'] . '/?$','wp-login.php?' . $oketheme['custom_login']['slug'] . '=1','top');

        // Kalau user sudah login dan buka wp-login.php/myadmin → redirect dashboard
        if ( is_user_logged_in() && $pagenow === 'wp-login.php' && !isset($_GET['action']) ) {
            wp_redirect( admin_url() );
            exit;
        }

        // Izinkan action=logout tetap berjalan normal
        if ( $pagenow === 'wp-login.php' && isset($_GET['action']) && $_GET['action'] === 'logout' ) {
            return;
        }

        // Kalau belum login dan akses wp-login.php langsung (GET) tanpa parameter → redirect ke homepage
        if (
            $pagenow === 'wp-login.php'
            && $_SERVER['REQUEST_METHOD'] === 'GET'
            && !isset($_GET[$oketheme['custom_login']['slug']])
            && !isset($_GET['action'])
        ) {
            wp_redirect( home_url() );
            exit;
        }

        if ( is_admin() && !is_user_logged_in() && !( defined('DOING_AJAX') && DOING_AJAX ) ) {
            wp_redirect( home_url() );
            exit;
        }
    }
});

// Template Redirect
add_action('template_redirect', function() {
    // PDF Template
    if (get_query_var('pdf_url')) {
        $fileId = $_GET['fileId'];
        $pdfURL = "https://drive.google.com/uc?export=download&id=" . $fileId;
        header("Content-Type: application/pdf");
        echo file_get_contents($pdfURL);
        exit;
    }
});

// Custom Login CSS
add_action('login_enqueue_scripts', function() {
    global $oketheme; 
    echo '<style>
        :root {
            --color1: '.$oketheme['color1'].';
            --color2: '.$oketheme['color2'].';
        }
        '.($oketheme['logo_web']?'
            .login h1 a {
                background-image: url("'.$oketheme['logo_web'].'")!important;
                background-size: contain!important;
                width: 250px!important;
                display: block!important;
                height: 70px!important;
                margin: 0 auto 20px!important;
            }
        ':'
            .login h1 {
                display: none;
            }
            .login form p:first-child:before {
                content: "'.$oketheme['nama_web'].'";
                font-size: 30px;
                margin: -10px 0 20px;
                display: block;
                font-weight: 700;
                text-align: center;
            }
        ').'
        '.($oketheme['custom_login']['layout'] != 'std'?'
            body.login:before {
                content: "";
                position: absolute;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                z-index: -1;
                opacity: .5;
                background-image: url("'.$oketheme['custom_login']['bg']['background-image']['url'].'");
                background-position: '.$oketheme['custom_login']['bg']['background-position'].';
                background-repeat: '.$oketheme['custom_login']['bg']['background-repeat'].';
                background-attachment: '.$oketheme['custom_login']['bg']['background-attachment'].';
                background-size: '.$oketheme['custom_login']['bg']['background-size'].';
            }
        ':'').'
    </style>';

    if (empty($oketheme['custom_login']['act'])) return;
    
    if($oketheme['custom_login']['layout'] == 'layout1') {
        wp_enqueue_style('custom-login', get_stylesheet_directory_uri() . '/assets/css/login1.css', array('login'), null);
    } else if($oketheme['custom_login']['layout'] == 'layout2') {
        wp_enqueue_style('custom-login', get_stylesheet_directory_uri() . '/assets/css/login2.css', array('login'), null);
        echo '<style>
            '.(!$oketheme['logo_web']?'
                .login h1 a, .login form p:first-child:before {
                    display: none!important;
                }
                .login h1:before {
                    content: "'.$oketheme['nama_web'].'";
                    font-size: 40px;
                    display: block;
                    font-weight: 700;
                    background: var(--color1);
                    border-top-left-radius: 12px;
                    border-top-right-radius: 12px;
                }
                .login h1:after {
                    content: "'.$oketheme['slogan_web'].'";
                    font-size: 20px;
                    font-weight: normal;
                    background: var(--color2);
                    border-bottom-left-radius: 12px;
                    border-bottom-right-radius: 12px;
                }
            ':'').'
        </style>';
    }
}, 99);

// Telpon 62
function indo62($x) {
	if (substr($x, 0, 1) === '0') {
		$x = substr_replace($x, '62', 0, 1);
	}
	return $x;
}

// Post Views Oketheme
function getPostViews($postID){
    $count_key = 'post_views_count';
    $count = get_post_meta($postID, $count_key, true);
    if($count==''){
        delete_post_meta($postID, $count_key);
        add_post_meta($postID, $count_key, '0');
        return '0';
    } else {
		$count = number_format($count,0,',','.');
	}
    return $count.'';
}
function setPostViews($postID) {
    $count_key = 'post_views_count';
    $count = get_post_meta($postID, $count_key, true);
    if($count==''){
        $count = 0;
        delete_post_meta($postID, $count_key);
        add_post_meta($postID, $count_key, '0');
    }else{
        $count++;
        update_post_meta($postID, $count_key, $count);
    }
}
add_filter('manage_posts_columns', 'posts_column_views');
function posts_column_views($defaults){
    $defaults['post_views'] = __('Dilihat', 'oketheme');
    return $defaults;
}
add_action('manage_posts_custom_column', 'posts_custom_column_views',5,2);
function posts_custom_column_views($column_name, $id){
	if($column_name === 'post_views'){
        echo getPostViews(get_the_ID());
    }
}

// Get Language File & Execute
add_action('wp_loaded', 'lang_act');
function lang_act() {
	if (!is_admin()) {
		global $oketheme;
		if(isset($oketheme['lang'])) {
			@include_once get_template_directory() . '/lang/'.$oketheme['lang'].'.php';
		} else {
            include_once get_template_directory() . '/lang/indonesia.php';
        }
	}
}
function lang_list() {
	$dir = get_template_directory().'/lang'; 
	if ($handle = opendir($dir)) {
		$value 	= array ();
		$text 	= array ();
		while (false !== ($file = readdir($handle))) {
			if ($file != "." && $file != ".." && strtolower(substr($file, strrpos($file, '.') + 1)) == 'php')  {
				$value[]	= basename($file, '.php');
				$text[]		= ucfirst(basename($file, '.php'));
			}
		}
		$lang	= array_combine($value,$text);
		return $lang;
		closedir($handle);
	}
}

// Customizer Remove No Need panel
add_action('customize_register', function ($wp_customize) {
    // Hapus Site Identity
    $wp_customize->remove_section('title_tagline');

    // Hapus Homepage Settings
    $wp_customize->remove_section('static_front_page');

}, 20);

// Customizer Panel Connection
add_action('customize_controls_print_footer_scripts', function() { ?>
    <script>
        jQuery(document).ready(function($) {
            if (window.self !== window.top) return;
            window.addEventListener('message', function(event) {
                if (event.origin !== window.location.origin) return;
                var data = event.data;
                if (data.id) {
                    wp.customize.section(data.id).focus();
                }
            });
        });
    </script>
    <?php
});

// Icon Menu
add_action( 'init', function() {
    if( class_exists( 'CSF' ) ) {
        $prefix = 'warta_menu';
        CSF::createNavMenuOptions( $prefix, array(
            'data_type' => 'serialize',
        ) );
        CSF::createSection( $prefix, array(
            'fields' => array(
                array(
                    'id'    => 'icon',
                    'type'  => 'icon',
                    'title' => 'Icon',
                ),
            )
        ) );
    }
} );
add_filter( 'wp_nav_menu_objects', function( $items, $args ) {
    foreach ( $items as &$item ) {
        $meta = get_post_meta( $item->ID, oke_slug().'_menu', true );
        if( ! empty( $meta['icon'] ) ) {
            $item->title = '<i class="'. $meta['icon'] .'"></i>' . $item->title;
        }
    }
    return $items;
} , 10, 2 );

// Convert to WebP
function convert_to_webp($metadata, $attachment_id) {
    global $oketheme;
    if(!$oketheme['convert_webp_act']) return $metadata;
    if (get_transient('convertwebp_status') !== '1') return $metadata;

    $upload_dir = wp_upload_dir();
    $base_dir = $upload_dir['basedir'];
    $file_path = $base_dir . '/' . $metadata['file'];
    $file_info = pathinfo($file_path);

    // Konversi file utama ke WebP
    $webp_main = $file_info['dirname'] . '/' . $file_info['filename'] . '.webp';

    if (convert_image_to_webp($file_path, $webp_main) && file_exists($webp_main)) {
        // Perbarui metadata agar menggunakan WebP
        $metadata['file'] = str_replace($file_info['basename'], $file_info['filename'] . '.webp', $metadata['file']);
        
        // Hapus file asli
        unlink($file_path);
        
        // Perbarui informasi file di database
        $webp_url = str_replace($upload_dir['basedir'], $upload_dir['baseurl'], $webp_main);
        wp_update_post([
            'ID' => $attachment_id,
            'guid' => $webp_url // Pastikan URL di database adalah WebP
        ]);
        
        // Perbarui meta file asli agar WordPress tidak mencari format lama
        update_post_meta($attachment_id, '_wp_attached_file', str_replace($upload_dir['basedir'] . '/', '', $metadata['file']));
    }

    // Konversi semua ukuran gambar
    foreach ($metadata['sizes'] as $size => $data) {
        $original_size_path = $file_info['dirname'] . '/' . $data['file'];
        $webp_size_path = preg_replace('/\.(jpg|jpeg|png|gif)$/i', '.webp', $original_size_path);

        if (convert_image_to_webp($original_size_path, $webp_size_path) && file_exists($webp_size_path)) {
            $metadata['sizes'][$size]['file'] = basename($webp_size_path);
            unlink($original_size_path);
        }
    }

    return $metadata;
}
add_filter('wp_generate_attachment_metadata', 'convert_to_webp', 10, 2);
function convert_image_to_webp($source, $destination) {
    if (!file_exists($source)) return false;

    $image_info = getimagesize($source);
    $mime = $image_info['mime'];

    switch ($mime) {
        case 'image/jpeg':
            $image = imagecreatefromjpeg($source);
            break;
        case 'image/png':
            $image = imagecreatefrompng($source);
            imagepalettetotruecolor($image);
            imagealphablending($image, false);
            imagesavealpha($image, true);
            break;
        default:
            return false;
    }

    if (isset($image)) {
        imagewebp($image, $destination, 80);
        imagedestroy($image);
        return file_exists($destination);
    }

    return false;
}

// PWA
add_action('init', function () {
    global $oketheme;
    if ( isset( $oketheme['pwa_act'] ) && $oketheme['pwa_act'] ) {
        include_once( get_stylesheet_directory() . '/inc/pwa/pwa.php' );
    }
});





