<?php 

/* 

Please do not edit this file as it may cause errors.
Melakukan modifikasi/edit pada file ini dapat menyebabkan error atau kerusakan fungsi dari theme.

*/

// Theme Head
add_action( 'wp_head', 'theme_head');
function theme_head() {
    global $oketheme;

    // Favicon
    if($oketheme['fav_web']) {
        echo '<link href="'.$oketheme['fav_web'].'" type="image/x-icon" rel="icon" />';
    }

    // Dark Mode
    if ($oketheme['dark_mode']['act'] && ((isset($_COOKIE['warta_dark']) && $_COOKIE['warta_dark'] == '1') || (!isset($_COOKIE['warta_dark']) && $oketheme['dark_mode']['default']))) { ?>
        <link rel="stylesheet" type="text/css" href="<?php echo get_template_directory_uri(); ?>/assets/css/dark.css" id="darkmode-stylesheet" /> 
    <?php }

    // Responsive
    if ($oketheme['responsive_act']) { ?>
		<link rel="stylesheet" type="text/css" href="<?php echo get_template_directory_uri(); ?>/assets/css/responsive.css" media="all" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
	<?php } else { ?>
        <meta name="viewport" content="width=1092" />
        <style>
            body {min-width: 1092px}
            .banner-floating._side {display: none;}
        </style>
    <?php }

    // Font Family
	if ($oketheme['typography']['type'] == 'google') { ?>
		<link href="https://fonts.googleapis.com/css2?family=<?=$oketheme['typography']['font-family'];?>:wght@400;500;600;700&display=swap" rel="stylesheet">
	<?php } ?>

    <!-- CSS -->
    <style type="text/css">

        /* Root Custom */
        :root {
            --color1: <?=$oketheme['color1'];?>;
            --color2: <?=$oketheme['color2'];?>;
            <?=$oketheme['corner_style']=='flat'?'--bradius: 0;':'';?>
        }

        /* Posisi Sidebar */
        <?php if($oketheme['sidebar_lr']=='left') {
            echo '#content { flex-direction:row-reverse; }';
        } ?>
        <?php if(!empty($oketheme['htop']['feat_blog']['bg_act'])) { ?>
            #feat-blog._bg { 
                background: linear-gradient(<?=$oketheme['htop']['feat_blog']['bg']['background-gradient-direction'];?>, <?=$oketheme['htop']['feat_blog']['bg']['background-color'];?> 33%, <?=$oketheme['htop']['feat_blog']['bg']['background-gradient-color'];?>); 
            }
            <?php if(!empty($oketheme['htop']['feat_blog']['bg']['background-image']['url'])) { ?>
                #feat-blog._bg:before {
                    background-image: url('<?=$oketheme['htop']['feat_blog']['bg']['background-image']['url'];?>');
                }
            <?php }
        } ?>

        /* Custom CSS */
        <?=$oketheme['custom_css']?:'';?>

    </style>
    
    <!-- Header Code -->
    <?=$oketheme['header_code']?:'';?>

<?php }

// Theme Footer
add_action( 'wp_footer', 'theme_footer');
function theme_footer() {
    global $oketheme; ?>

    <!-- Auto Popup -->
    <?php if (!$oketheme['popup_home'] || (is_home() && is_main_query())) {
        autopopup();
    } ?>
    
    <!-- Scroll Up -->
    <span class="scrollup"><i class="m-icon">expand_less</i></span>

    <!-- Footer Code -->
    <?=$oketheme['footer_code']?:'';?>

    <!-- JS Variable -->
    <script type="text/javascript">
        themeDir = '<?php echo get_template_directory_uri(); ?>';
        darkDefault = '<?php echo $oketheme['dark_mode']['act'] && $oketheme['dark_mode']['default']?true:false; ?>';
        logoLight = '<?php echo $oketheme['logo_web']?:false; ?>';
        logoDark = '<?php echo $oketheme['dark_mode']['act'] && $oketheme['dark_mode']['logo_act'] && $oketheme['dark_mode']['logo_web']?$oketheme['dark_mode']['logo_web']:false; ?>';
        optUrl = '<?php echo admin_url('admin.php?page='.oke_slug().'-options#tab='); ?>';
        cusUrl = '<?php echo admin_url('customize.php'); ?>';

        <?php if ($oketheme['disclick_act']) { ?>
            jQuery(document).ready(function($) {
                $(document).on("contextmenu", function(event) {
                    event.preventDefault();
                    alert("<?php _e('Maaf, klik kanan dinonaktifkan pada website ini.', 'oketheme'); ?>");
                });
            });
        <?php } ?>
	</script>

    <!-- PWA -->
    <?php if($oketheme['pwa_act']) { ?>
        <button id="installAppBtn" class="pwa-bttn" style="display:none" title="<?=wp_is_mobile()?'Mobile':'Desktop';?>"><i class="m-icon"><?=wp_is_mobile()?'install_mobile':'install_desktop';?></i> <?= __('Pasang Aplikasi','oketheme'); ?></button>
    <?php }
}

// Auto Popup
function autopopup() {
    global $oketheme;
    if ($oketheme['popup_act']) { ?>
		<a href="#autopopup" class="autopop"></a>
		<div id="autopopup" class="popup">
			<?php 
			//Facebook Fanpage
			if ($oketheme['popup_act'] == 'fb' && $oketheme['popup_fb']) { ?>
				<iframe src="https://www.facebook.com/plugins/page.php?href=<?=$oketheme['popup_fb']; ?>&tabs=messages&width=290&height=300&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true" width="290" height="300" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
			<?php } 
			// Gambar
			else if ($oketheme['popup_act'] == 'img' && $oketheme['popup_img']['url']) {
				echo $oketheme['popup_img']['url'] && $oketheme['popup_img_link']?'<a href="'.$oketheme['popup_img_link'].'" target="blank">':'';
				echo '<img style="display:block" src="'.$oketheme['popup_img']['url'].'" alt="'.$oketheme['popup_img']['alt'].'" width="'.$oketheme['popup_img']['width'].'" height="'.$oketheme['popup_img']['height'].'">';
				echo $oketheme['popup_img']['url'] && $oketheme['popup_img_link']?'</a>':'';
			} 
			// Youtube Video
			else if ($oketheme['popup_act'] == 'youtube' && $oketheme['popup_youtube']) { ?>
				<iframe width="600" height="320" src="https://www.youtube.com/embed/<?=get_yID($oketheme['popup_youtube']); ?>?autoplay=0&rel=0" frameborder="0" allowfullscreen></iframe>
			<?php } 
			// Tiktok
			else if ($oketheme['popup_act'] == 'tiktok' && $oketheme['popup_tiktok']) { ?>
				<?php $tik = json_decode(ocurl('https://www.tiktok.com/oembed?url=' . $oketheme['popup_tiktok']), true); echo $tik['html'];?>
			<?php } 
			// HTML
			else if ($oketheme['popup_act'] == 'html' && $oketheme['popup_html']) {
				echo $oketheme['popup_html']; ?>
			<?php } else {
                echo '<b>Perhatian:</b> Terjadi kesalahan, cek kembali pengaturan fitur Popup pada theme options.';
            } ?>
		</div>
	<?php }
}

// Flash Blog (Breaking News)
function flash_blog() {
    global $oketheme;
    if(!empty($oketheme['flash_blog']['act'])) {
        $args = array(
            'post_type' => 'post',
            'showposts' => 6,
            'ignore_sticky_posts' => true,
        );
        if (!empty($oketheme['flash_blog']['cat'])) {
            $args['cat'] = $oketheme['flash_blog']['cat'];
        } else {
            $args['orderby'] = 'rand';
        }
        $the_query = new WP_Query($args); 
        if(!$the_query->have_posts()) return the_current_day();
        ?>

        <div id="flash-blog" class="flexcon gap-10" <?=$oketheme['topsearch_act']?'':'style="width:100%"'?> data-customize-partial-id="header" data-helper-title="Breaking News" data-helper-tab="header">
            <?php if($oketheme['flash_blog']['title']) { ?>
                <div class="_title">
                    <?php echo $oketheme['flash_blog']['title']; ?>
                </div>
            <?php } ?>
            <div class="splide">
                <div class="splide__track">
                    <ul class="splide__list">
                        <?php while ($the_query->have_posts()):$the_query->the_post(); 
                            echo '<li class="splide__slide elipsis"><a title="'.get_the_title().'" href="'.get_the_permalink().'">'.get_the_title().'</a></li>';
                        endwhile;?>
                    </ul>
                </div>
            </div>
        </div>
        <?php wp_reset_postdata();
    } else {
        the_current_day();
    }
}

// Headline Blog
function head_blog() {
    global $oketheme;
    if(!empty($oketheme['htop']['head_blog']['act'])) {
        $args = array(
            'post_type' => 'post',
            'ignore_sticky_posts' => true,
        );
        if (!empty($oketheme['htop']['head_blog']['post']) && $oketheme['htop']['head_blog']['act'] == 'post') {
            $args['post__in'] = $oketheme['htop']['head_blog']['post'];
            $args['orderby']  = 'post__in';
        } else if (!empty($oketheme['htop']['head_blog']['cat']) && $oketheme['htop']['head_blog']['act'] == 'cat') {
            $args['cat'] = $oketheme['htop']['head_blog']['cat'];
            $args['showposts'] = 6;
        }else {
            $args['showposts'] = 6;
        }
        $the_query = new WP_Query($args); ?>
        <?php if ($the_query->have_posts()) { ?>
            <div id="head-blog" class="mega splide" data-customize-partial-id="beranda-atas" data-helper-title="Headline" data-helper-tab="beranda/atas">
                <div class="splide__track">
                    <ul class="splide__list">
                        <?php while ($the_query->have_posts()):$the_query->the_post(); 
                            echo '<li class="splide__slide">'; loop('medium_large'); echo '</li>';
                        endwhile; wp_reset_postdata();?>
                    </ul>
                </div>
            </div>
        <?php } 
    }
}

// Featured Blog
function featured_blog() {
    global $oketheme;
    if(!empty($oketheme['htop']['feat_blog']['post']) && $oketheme['htop']['feat_blog']['act']) {
        $args = array(
            'post__in'  => $oketheme['htop']['feat_blog']['post'],
            'orderby'   => 'post__in',
            'ignore_sticky_posts' => true,
        );
        $the_query = new WP_Query($args); ?>
        <?php if ($the_query->have_posts()) { ?>
            <div id="feat-blog" class="<?=!empty($oketheme['htop']['feat_blog']['bg_act'])?'_bg bgtrans':'_nobg';?> box-content" data-customize-partial-id="beranda-atas" data-helper-title="Post Unggulan" data-helper-tab="beranda/atas">
                <div class="_title">
                    <h2><?=$oketheme['htop']['feat_blog']['title']?:__('Post Unggulan','oketheme'); ?></h2>
                </div>
                <div class="splide post-slider">
                    <div class="splide__track">
                        <ul class="splide__list">
                            <?php while ($the_query->have_posts()):$the_query->the_post(); 
                                echo '<li class="splide__slide">'; loop('regular'); echo '</li>';
                            endwhile; wp_reset_postdata();?>
                        </ul>
                    </div>
                </div>
            </div>
        <?php } 
    }
}

// Featured Category #1
function featured_cat() {
    global $oketheme;
    if(!empty($oketheme['htop']['feat_cat']['cat']) && $oketheme['htop']['feat_cat']['act']) { ?>
        <div id="feat-cat" class="box-content" data-customize-partial-id="beranda-atas" data-helper-title="Kategori Unggulan" data-helper-tab="beranda/atas">
            <div class="_title justify-between gap-10">
                <h2><?=$oketheme['htop']['feat_cat']['title']?:__('Kategori Unggulan','oketheme'); ?></h2>
                <div class="hscroll oketabs-bttns">
                    <?php foreach ($oketheme['htop']['feat_cat']['cat'] as $cat) {
                        $cat_name = get_cat_name($cat);
                        echo '<button class="oketabs-bttn">'.$cat_name.'</button>';
                    } ?>
                </div>
            </div>
            <div class="oketabs">
                <div class="oketabs-panels">
                    <?php foreach ($oketheme['htop']['feat_cat']['cat'] as $cat) {
                        $cat_link = get_category_link($cat);
                        $cat_name = get_cat_name($cat);
                        $args = array(
                            'showposts' => $oketheme['htop']['feat_cat']['count'],
                            'cat' => $cat,
                            'ignore_sticky_posts' => true,
                        );
                        $the_query = new WP_Query($args);

                        if ($the_query->have_posts()) { ?>
                            <div class="oketabs-panel">
                                <div class="grid three-col">
                                    <?php while ($the_query->have_posts()):$the_query->the_post(); loop('medium'); endwhile; wp_reset_postdata();?>
                                </div>
                                <a href="<?php echo $cat_link; ?>" class="_more">&raquo; <?php _e('Lihat Semua','oketheme'); ?>: <?php echo '<u>'.$cat_name.'</u>'; ?></a>
                            </div>
                        <?php } else { ?>
                            <div class="oketabs-panel">
                                <p><?php _e('Maaf, saat ini belum tersedia post untuk ditampilkan.', 'oketheme'); ?></p>
                            </div>
                        <?php }
                    } ?>
                </div>
            </div>
        </div>
    <?php }
}

// Latest Blog
function latest_blog() {
    global $oketheme;
    if($oketheme['hbot']['latest_blog']['act']) {
        $mode = $oketheme['hbot']['latest_blog']['mode'];
        switch ($mode) {
            case 'mixed': $class = 'grid mixed three-col _res'; break;
            case 'list': $class = 'list _res'; break;
            case 'carousel': $class = 'carousel'; break;
            default: $class = 'grid three-col _res'; break;
        }
        $args = array(
            'showposts' => $oketheme['hbot']['latest_blog']['count'],
            'ignore_sticky_posts' => true,
        );
        $the_query = new WP_Query($args); ?>
        <div id="latest-blog" class="box-content" data-customize-partial-id="beranda-bawah" data-helper-title="Post Terbaru" data-helper-tab="beranda/bawah">
            <div class="_title">
                <h2><?=$oketheme['hbot']['latest_blog']['title']?:__('Post Terbaru','oketheme'); ?></h2>
                <?php if($mode != 'carousel') { ?>
                    <a class="_more" href="<?php echo get_site_url().'/index-berita'; ?>">&raquo; <?php _e('Lihat Semua','oketheme'); ?></a>
                <?php } ?>
            </div>
            <?php if ($the_query->have_posts()) {
                if($mode == 'carousel') { ?>
                    <div class="post-slider _regular splide">
                        <div class="splide__track">
                            <ul class="splide__list">
                                <?php while ($the_query->have_posts()):$the_query->the_post(); 
                                    echo '<li class="splide__slide">'; loop('regular'); echo '</li>';
                                endwhile;?>
                            </ul>
                        </div>
                    </div>
                <?php } else { ?>
                    <div class="<?=$class; ?>">
                        <?php while ($the_query->have_posts()):$the_query->the_post(); loop('regular'); endwhile; wp_reset_postdata();?>
                    </div>
                <?php } 
            } else { ?>
                <p><?php _e('Maaf, saat ini belum tersedia post untuk ditampilkan.', 'oketheme'); ?></p>
            <?php } ?>
        </div>
    <?php }
}

// Featured Category #2
function featured_cat2() {
    global $oketheme;
    if(!empty($oketheme['hbot']['feat_cat']['cat']) && $oketheme['hbot']['feat_cat']['act']) {
        foreach ($oketheme['hbot']['feat_cat']['cat'] as $cat) {
            $cat_link = get_category_link($cat);
            $cat_name = get_cat_name($cat);

            $args = array(
                'showposts' => 6,
                'cat' => $cat,
                'ignore_sticky_posts' => true,
            );
            $the_query = new WP_Query($args);?>
    
            <div id="feat-cat2" class="box-content" data-customize-partial-id="beranda-bawah" data-helper-title="Kategori Unggulan" data-helper-tab="beranda/bawah">
                <div class="_title">
                    <h2><?=$cat_name; ?></h2>
                </div>
                <?php if ($the_query->have_posts()) { ?>
                    <div class="post-slider _regular splide">
                        <div class="splide__track">
                            <ul class="splide__list">
                                <?php while ($the_query->have_posts()):$the_query->the_post(); 
                                    echo '<li class="splide__slide">'; loop('regular'); echo '</li>';
                                endwhile;?>
                            </ul>
                        </div>
                    </div>
                    <a href="<?php echo $cat_link; ?>" class="_more">&raquo; <?php _e('Lihat Semua','oketheme'); ?>: <?php echo '<u>'.$cat_name.'</u>'; ?></a>
                <?php } else { ?>
                    <p>
                        <?php _e('Maaf, saat ini belum tersedia post untuk ditampilkan.', 'oketheme'); ?>
                    </p>
                <?php } ?>
            </div>
        <?php }
    }
}

// Rekomendasi Blog
function recommended_blog() {
    global $oketheme;
    if(!empty($oketheme['hbot']['recom_blog']['act'])) {
        $args = array(
            'showposts' => $oketheme['hbot']['recom_blog']['count'],
            'orderby' => 'rand',
            'ignore_sticky_posts' => true,
        );
        $the_query = new WP_Query($args);?>

        <div id="recom-blog" class="box-content" data-customize-partial-id="beranda-bawah" data-helper-title="Post Rekomendasi" data-helper-tab="beranda/bawah">
            <div class="_title">
                <h2><?=$oketheme['hbot']['recom_blog']['title']?:__('Rekomendasi','oketheme'); ?></h2>
            </div>
            <?php if ($the_query->have_posts()) { ?>
                <div class="list">
                    <?php while ($the_query->have_posts()):$the_query->the_post(); loop('thumbnail'); endwhile; wp_reset_postdata();?>
                </div>
            <?php } else { ?>
                <p>
                    <?php _e('Maaf, saat ini belum tersedia post untuk ditampilkan.', 'oketheme'); ?>
                </p>
            <?php } ?>
        </div>
    <?php }
}

// Latest ePaper
function latest_epaper() {
    global $oketheme;
    if(!empty($oketheme['epaper']['act']) && !empty($oketheme['epaper']['latest'])) {
        $args = array(
            'post_type' => $oketheme['epaper']['slug']?:'epaper',
            'showposts' => 6,
            'ignore_sticky_posts' => true,
        );
        $the_query = new WP_Query($args);?>

        <div id="latest-epaper" class="box-content" data-customize-partial-id="beranda-bawah" data-helper-title="ePaper Terbaru" data-helper-tab="beranda/bawah">
            <div class="_title">
                <h2><?=$oketheme['epaper']['title'].' '.__('Terbaru','oketheme'); ?></h2>
                <a class="_more" href="<?php echo get_site_url().'/'.$oketheme['epaper']['slug']; ?>">&raquo; <?php _e('Lihat Semua','oketheme'); ?></a>
            </div>
            <?php if ($the_query->have_posts()) { ?>
                <div class="grid three-col _res">
                    <?php while ($the_query->have_posts()):$the_query->the_post(); loop('regular','_epaper'); endwhile; wp_reset_postdata();?>
                </div>
            <?php } else { ?>
                <p>
                    <?php _e('Maaf, saat ini belum tersedia post untuk ditampilkan.', 'oketheme'); ?>
                </p>
            <?php } ?>
        </div>
    <?php }
}

// Video Blog
function video_blog() {
    global $oketheme;
    if(!empty($oketheme['hbot']['video_blog']['act'])) {
        $args = array(
            'showposts' => $oketheme['hbot']['video_blog']['count'],
            'ignore_sticky_posts' => true,
            'meta_query' => array(
                array(
                    'key'     => $oketheme['post_meta_video'],
                    'value'   => '',
                    'compare' => '!=',
                ),
            ),
        );
        $the_query = new WP_Query($args);?>

        <div id="video-blog" class="box-content" data-customize-partial-id="beranda-bawah" data-helper-title="Post Video" data-helper-tab="beranda/bawah">
            <div class="_title">
                <h2><?=$oketheme['hbot']['video_blog']['title']?:__('Video Terbaru','oketheme'); ?></h2>
            </div>
            <?php if ($the_query->have_posts()) { ?>
                <div class="grid two-col _res">
                    <?php while ($the_query->have_posts()):$the_query->the_post(); loop('medium'); endwhile; wp_reset_postdata();?>
                </div>
            <?php } else { ?>
                <p>
                    <?php _e('Maaf, saat ini belum tersedia post untuk ditampilkan.', 'oketheme'); ?>
                </p>
            <?php } ?>
        </div>
    <?php }
}

// Photo Blog
function photo_blog() {
    global $oketheme;
    if(!empty($oketheme['hbot']['photo_blog']['act'])) {
        $args = array(
            'showposts' => $oketheme['hbot']['photo_blog']['count'],
            'ignore_sticky_posts' => true,
            'meta_query' => array(
                array(
                    'key'     => $oketheme['post_meta_gallery'],
                    'value'   => '',
                    'compare' => '!=',
                ),
            ),
        );
        $the_query = new WP_Query($args);?>

        <div id="photo-blog" class="box-content" data-customize-partial-id="beranda-bawah" data-helper-title="Post Foto" data-helper-tab="beranda/bawah">
            <div class="_title">
                <h2><?=$oketheme['hbot']['photo_blog']['title']?:__('Foto Terbaru','oketheme'); ?></h2>
            </div>
            <?php if ($the_query->have_posts()) { ?>
                <div class="grid three-col _res">
                    <?php while ($the_query->have_posts()):$the_query->the_post(); loop('regular'); endwhile; wp_reset_postdata();?>
                </div>
            <?php } else { ?>
                <p>
                    <?php _e('Maaf, saat ini belum tersedia post untuk ditampilkan.', 'oketheme'); ?>
                </p>
            <?php } ?>
        </div>
    <?php }
}

// Trending Blog :: Sidebar
function trending_blog() {
    global $oketheme;
    if(!empty($oketheme['sidebar']['trending_blog']['act'])) {
        $args = array(
            'posts_per_page' => $oketheme['sidebar']['trending_blog']['count'],
            'meta_key'       => 'post_views_count',
            'orderby'        => 'meta_value_num',
            'order'          => 'DESC',  
            'ignore_sticky_posts' => true,
        );
        if ($oketheme['sidebar']['trending_blog']['period'] !== 'all') {
            $date_query = array(
                array(
                    'after'     => $oketheme['sidebar']['trending_blog']['period'],
                    'inclusive' => true,
                ),
            );
            $args['date_query'] = $date_query;
        }
        $the_query = new WP_Query($args);?>
        <div id="trending-blog"class="box-content" data-customize-partial-id="sidebar" data-helper-title="Post Populer" data-helper-tab="sidebar">
            <div class="_title">
                <h4><?=$oketheme['sidebar']['trending_blog']['title']?:__('Terpopuler','oketheme'); ?></h4>
            </div>
            <?php if ($the_query->have_posts()) {
                echo '<ol class="list">';
                $count = 0; // Counter untuk melacak iterasi
                while ($the_query->have_posts()):
                    $the_query->the_post();
                    if ($count === 0) {
                        // Postingan pertama menggunakan template berbeda
                        loop('regular');
                    } else {
                        // Postingan lainnya menggunakan template standar
                        loop('thumbnail');
                    }
                    $count++;
                endwhile;
                echo '</ol>';
                wp_reset_postdata(); 
            } else { ?>
                <p><?php _e('Maaf, saat ini belum tersedia post untuk ditampilkan.', 'oketheme'); ?></p>
            <?php } ?>
        </div>
    <?php }
}

// Top Comment Blog: Sidebar
function top_comment_blog() {
    global $oketheme;
    if(!empty($oketheme['sidebar']['comment_blog']['act'])) {
        $args = array(
            'posts_per_page' => $oketheme['sidebar']['comment_blog']['count'],
            'orderby'        => 'comment_count',
            'order'          => 'DESC',  
            'ignore_sticky_posts' => true,
            'comment_count'       => array(
                'value'   => 0,
                'compare' => '>',
            ),
        );
        if ($oketheme['sidebar']['comment_blog']['period'] !== 'all') {
            $date_query = array(
                array(
                    'after'     => $oketheme['sidebar']['comment_blog']['period'],
                    'inclusive' => true,
                ),
            );
            $args['date_query'] = $date_query;
        }
        $the_query = new WP_Query($args); ?>
        <div id="top-comment-blog" class="box-content" data-customize-partial-id="sidebar" data-helper-title="Komentar Terbanyak" data-helper-tab="sidebar">
            <div class="_title">
                <h4><?=$oketheme['sidebar']['comment_blog']['title']?:__('Komentar Terbanyak','oketheme'); ?></h4>
            </div>
            <?php if ($the_query->have_posts()) { ?>
                <div class="list">
                    <?php while ($the_query->have_posts()):$the_query->the_post(); loop('thumbnail'); endwhile; wp_reset_postdata();?>
                </div>
            <?php } else { ?>
                <p><?php _e('Maaf, saat ini belum tersedia post untuk ditampilkan.', 'oketheme'); ?></p>
            <?php } ?>
        </div>
    <?php }
}

// Latest Blog: Sidebar
function slatest_blog() {
    global $oketheme;
    if((is_home() && !$oketheme['sidebar']['latest_blog']['hide_home']) || !is_home()) {
        if($oketheme['sidebar']['latest_blog']['act']) {
            $args = array(
                'posts_per_page' => $oketheme['sidebar']['latest_blog']['count'],
                'ignore_sticky_posts' => true,
            );
            $the_query = new WP_Query($args); ?>
            <div id="slatest-blog" class="box-content" data-customize-partial-id="sidebar" data-helper-title="Post Terbaru" data-helper-tab="sidebar">
                <div class="_title">
                    <h4><?=$oketheme['sidebar']['latest_blog']['title']?:__('Terbaru','oketheme'); ?></h4>
                </div>
                <?php if ($the_query->have_posts()) { ?>
                    <div class="list">
                    <?php while ($the_query->have_posts()):$the_query->the_post(); loop('thumbnail'); endwhile; wp_reset_postdata();?>
                    </div>
                <?php } else { ?>
                    <p><?php _e('Maaf, saat ini belum tersedia post untuk ditampilkan.', 'oketheme'); ?></p>
                <?php } ?>
            </div>
        <?php }
    }
}

// Related @ Content (Baca Juga)
function related_content() {
    global $oketheme;
    if (!$oketheme['read_also_act']) return;

    $category_ids = wp_get_post_categories(get_the_ID());
    $tag_ids = wp_get_post_tags(get_the_ID(), array('fields' => 'ids'));

    if (empty($category_ids) && empty($tag_ids)) return;

    $related_posts = new WP_Query(array(
        'post_type'           => 'post',
        'posts_per_page'      => 2,
        'orderby'             => 'rand',
        'post__not_in'        => array(get_the_ID()),
        'ignore_sticky_posts' => true,
        'tax_query'           => array(
            'relation' => 'OR',
            !empty($category_ids) ? array(
                'taxonomy' => 'category',
                'field'    => 'term_id',
                'terms'    => $category_ids,
            ) : null,
            !empty($tag_ids) ? array(
                'taxonomy' => 'post_tag',
                'field'    => 'term_id',
                'terms'    => $tag_ids,
            ) : null,
        ),
    ));

    if (!$related_posts->have_posts()) return;

    echo '<div id="related-posts" style="display:none;">';

    while ($related_posts->have_posts()) {
        $related_posts->the_post();
        echo '<div class="related-content" data-customize-partial-id="single" data-helper-title="Baca Juga" data-helper-tab="single-post"><b>'.__('Baca juga', 'oketheme').': </b><a href="' . get_permalink() . '">' . get_the_title() . '</a></div>';
    }

    echo '</div>';
    wp_reset_postdata(); ?>
        <script>
            jQuery(document).ready(function ($) {
                var relatedPosts = $('#related-posts .related-content');
                var childDivs = $('.wrap-post._artikel').children();

                if (childDivs.length === 0 || relatedPosts.length === 0) return;

                if (childDivs.length < 6) {
                    relatedPosts.slice(1).remove();
                    var middleIndex = Math.floor(childDivs.length / 2);
                    relatedPosts.first().insertAfter(childDivs.eq(middleIndex - 1)).show();
                } else {
                    var firstIndex = Math.floor(childDivs.length / 5);
                    var secondIndex = Math.floor(4 * childDivs.length / 5);

                    relatedPosts.eq(0).insertAfter(childDivs.eq(firstIndex - 1)).show();
                    relatedPosts.eq(1).insertAfter(childDivs.eq(secondIndex - 1)).show();
                }

                // Hapus div kosong setelah pindah
                $('#related-posts').remove();
            });

        </script>
    <?php
}

// Related Blog
function related_blog() {
    global $oketheme;
    if (empty($oketheme['related_blog']['act'])) return;

    $category_ids = array();
    $tag_ids = array();

    // Mengambil ID kategori
    $categories = get_the_category();
    if (!empty($categories) && is_array($categories)) {
        foreach ($categories as $category) {
            $category_ids[] = $category->term_id;
        }
    }

    // Mengambil ID tag
    $tags = get_the_tags();
    if (!empty($tags) && is_array($tags)) {
        foreach ($tags as $tag) {
            $tag_ids[] = $tag->term_id;
        }
    }

    // Cek apakah ada kategori atau tag
    if (empty($category_ids) && empty($tag_ids)) return;

    // Membuat query untuk post terkait berdasarkan kategori ATAU tag
    $args = array(
        'post_type'             => 'post',
        'posts_per_page'        => 4,
        'post__not_in'          => array(get_the_ID()),
        'ignore_sticky_posts'   => true,
        'tax_query'             => array(
            'relation' => 'OR',
            !empty($category_ids) ? array(
                'taxonomy' => 'category',
                'field'    => 'term_id',
                'terms'    => $category_ids,
            ) : null,
            !empty($tag_ids) ? array(
                'taxonomy' => 'post_tag',
                'field'    => 'term_id',
                'terms'    => $tag_ids,
            ) : null,
        ),
    );

    // Hapus elemen null dari tax_query
    $args['tax_query'] = array_filter($args['tax_query']);

    $the_query = new WP_Query($args);
    if (!$the_query->have_posts()) return;
    ?>

    <div id="related-blog" class="box-content" data-customize-partial-id="single" data-helper-title="Post Terkait" data-helper-tab="single-post">
        <div class="_title">
            <h2><?=$oketheme['related_blog']['title']?:__('Post Terkait','oketheme'); ?></h2>
        </div>
        <div class="grid two-col">
            <?php while ($the_query->have_posts()): $the_query->the_post(); loop('thumbnail'); endwhile; ?>
        </div>
    </div>
    <?php
    wp_reset_postdata();
}

// Random Blog
function random_blog() {
    global $oketheme;
    if(empty($oketheme['random_blog']['act'])) return;
    $args = array(
        'post_type' => 'post',
        'showposts' => 6,
        'orderby' => 'rand',
        'post__not_in'	=> array(get_the_ID()),
        'ignore_sticky_posts' => true,
    );
    $the_query = new WP_Query($args); 
    if(!$the_query->have_posts()) return;
    ?>

    <div id="random-blog" class="box-content" data-customize-partial-id="single" data-helper-title="Post Random" data-helper-tab="single-post">
        <div class="_title">
            <h2><?=$oketheme['random_blog']['title']?:__('Rekomendasi','oketheme'); ?></h2>
        </div>
        <div class="post-slider _regular splide">
            <div class="splide__track">
                <ul class="splide__list">
                    <?php while ($the_query->have_posts()):$the_query->the_post(); 
                        echo '<li class="splide__slide">'; loop('regular'); echo '</li>';
                    endwhile;?>
                </ul>
            </div>
        </div>
    </div>
    <?php wp_reset_postdata();
}

// Random ePaper
function random_epaper() {
    global $oketheme;
    if($oketheme['epaper']['act'] && $oketheme['epaper']['random']){
        $args = array(
            'post_type' => $oketheme['epaper']['slug'],
            'showposts' => 6,
            'orderby' => 'rand',
            'post__not_in'	=> array(get_the_ID()),
            'ignore_sticky_posts' => true,
        );
        $the_query = new WP_Query($args); 
        if(!$the_query->have_posts()) return;
        ?>

        <div id="random-epaper" class="box-content" data-customize-partial-id="epaper" data-helper-title="ePaper Random" data-helper-tab="extra/epaper">
            <div class="_title">
                <h2><?=$oketheme['epaper']['title'].' '.__('Lainnya','oketheme'); ?></h2>
            </div>
            <div class="post-slider _regular splide">
                <div class="splide__track">
                    <ul class="splide__list">
                        <?php while ($the_query->have_posts()):$the_query->the_post(); 
                            echo '<li class="splide__slide">'; loop('regular', '_epaper'); echo '</li>';
                        endwhile;?>
                    </ul>
                </div>
            </div>
        </div>
        <?php wp_reset_postdata();
    }
}

// Detail Post
function the_info() {
    global $oketheme; 
    if (!rwmb_meta($oketheme['post_meta_writer']) && get_the_author_meta('description')) {?>
        <div class="info _info">
            <?php echo get_avatar(get_the_author_meta('user_email')); ?>
            <h4 class="nm-top nm-bottom"><?php _e('Penulis','oketheme');?> <?php the_author_posts_link(); ?></h4>
            <p class="nm-bottom"><?php the_author_meta('description'); ?></p>
        </div>
    <?php } else { ?>
        <ul class="nolist info _info flexcon column gap-10">
            <li><b><?php _e('Penulis','oketheme');?></b>: <?=rwmb_meta($oketheme['post_meta_writer'])?: get_the_author(); ?></li>
            <?php if (rwmb_meta($oketheme['post_meta_editor'])) {
                echo '<li><b>'.__('Editor','oketheme').'</b>: '.rwmb_meta($oketheme['post_meta_editor']).'</li>';
            } if (rwmb_meta($oketheme['post_meta_source'])) {
                echo '<li><b>'.__('Sumber','oketheme').'</b>: <a href="'.rwmb_meta($oketheme['post_meta_source']).'">'.rwmb_meta($oketheme['post_meta_source']).'</a></li>';
            } ?>
        </ul>
    <?php }
}

// Iklan Show Condition
function is_ads_active() {
    global $oketheme;
    foreach ($oketheme['ads_show'] as $page_type) {
        if (
            ($page_type === 'home' && is_home()) ||
            ($page_type === 'post' && is_single()) ||
            ($page_type === 'page' && is_page()) ||
            ($page_type === 'archive' && is_archive()) ||
            ($page_type === 'search' && is_search()) ||
            ($page_type === '404' && is_404()) ||
            ($page_type === 'attachment' && is_attachment())
        ) {
            return true;
        }
    }
    return false;
}

// Iklan Mobile: 300px
function ads_mobile() {
    global $oketheme;
    if(!is_ads_active()) return;
    if(!empty($oketheme['ads_mobile_act']) && wp_is_mobile()) { ?>
        <div class="banner-mobile" data-customize-partial-id="iklan" data-helper-title="Iklan Mobile" data-helper-tab="iklan-banner">
            <div class="_content flexcon align-center justify-center">
                <span class="_scroll flexcon gap-10 align-center justify-center"><?php _e('Scroll untuk melanjutkan','oketheme'); ?></span>
                <span class="_close">&times;</span>
                <?php if($oketheme['ads_mobile_act']=='img') {
                if($oketheme['ads_mobile_url']) { echo '<a href="'.$oketheme['ads_mobile_url'].'">';}
                    echo '<img src="'.$oketheme['ads_mobile_img']['url'].'" alt="'.($oketheme['ads_mobile_img']['alt']?:'ads mobile').'" width="'.$oketheme['ads_mobile_img']['width'].'" height="'.$oketheme['ads_mobile_img']['height'].'">';
                if($oketheme['ads_mobile_url']) { echo '</a>';}
            } else {
                echo $oketheme['ads_mobile_script'];
            } ?>
            </div>
        </div>
    <?php }
}

// Iklan Fullwidth Top: 1060px
function ads_fullwidth_top() {
    global $oketheme;
    if(!is_ads_active()) return;
    if(empty($oketheme['ads_fullwidth_top_act'])) return;?>
    <div class="banner" data-customize-partial-id="iklan" data-helper-title="Iklan Fullwidth #Atas" data-helper-tab="iklan-banner">
        <?php if($oketheme['ads_fullwidth_top_act']=='img') {
            if($oketheme['ads_fullwidth_top_url']) { echo '<a href="'.$oketheme['ads_fullwidth_top_url'].'">';}
                echo '<img src="'.$oketheme['ads_fullwidth_top_img']['url'].'" alt="'.($oketheme['ads_fullwidth_top_img']['alt']?:'ads fullwidth top').'" width="'.$oketheme['ads_fullwidth_top_img']['width'].'" height="'.$oketheme['ads_fullwidth_top_img']['height'].'">';
            if($oketheme['ads_fullwidth_top_url']) { echo '</a>';}
        } else {
            echo $oketheme['ads_fullwidth_top_script'];
        } ?>
    </div>
    <?php 
}

// Iklan Fullwidth Bottom: 1060px
function ads_fullwidth_bot() {
    global $oketheme;
    if(!is_ads_active()) return;
    if(empty($oketheme['ads_fullwidth_bottom_act'])) return;?>
    <div class="banner" data-customize-partial-id="iklan" data-helper-title="Iklan Fullwidth #Bawah" data-helper-tab="iklan-banner">
        <?php if($oketheme['ads_fullwidth_bottom_act']=='img') {
            if($oketheme['ads_fullwidth_bottom_url']) { echo '<a href="'.$oketheme['ads_fullwidth_bottom_url'].'">';}
                echo '<img src="'.$oketheme['ads_fullwidth_bottom_img']['url'].'" alt="'.($oketheme['ads_fullwidth_bottom_img']['alt']?:'ads fullwidth bottom').'" width="'.$oketheme['ads_fullwidth_bottom_img']['width'].'" height="'.$oketheme['ads_fullwidth_bottom_img']['height'].'">';
            if($oketheme['ads_fullwidth_bottom_url']) { echo '</a>';}
        } else {
            echo $oketheme['ads_fullwidth_bottom_script'];
        } ?>
    </div>
    <?php 
}

// Iklan Konten #Top: 728px
function ads_content_top() {
    global $oketheme;
    if(!is_ads_active()) return;
    if(empty($oketheme['ads_content_top_act'])) return;?>
    <div class="banner" data-customize-partial-id="iklan" data-helper-title="Iklan Konten #Atas" data-helper-tab="iklan-banner">
        <?php if($oketheme['ads_content_top_act']=='img') {
            if($oketheme['ads_content_top_url']) { echo '<a href="'.$oketheme['ads_content_top_url'].'">';}
                echo '<img src="'.$oketheme['ads_content_top_img']['url'].'" alt="'.($oketheme['ads_content_top_img']['alt']?:'ads content top').'" width="'.$oketheme['ads_content_top_img']['width'].'" height="'.$oketheme['ads_content_top_img']['height'].'">';
            if($oketheme['ads_content_top_url']) { echo '</a>';}
        } else {
            echo $oketheme['ads_content_top_script'];
        } ?>
    </div>
    <?php 
}

// Iklan Konten #Middle: 728px
add_action('wp_footer', function() {
    global $oketheme;
    if(!is_ads_active()) return;
    if(empty($oketheme['ads_content_middle_act'])) return;?>
    <div class="banner-parallax" data-customize-partial-id="iklan" data-helper-title="Iklan Konten #Tengah" data-helper-tab="iklan-banner">
        <div class="_content <?=$oketheme['ads_content_middle_parallax']?'_on':'';?>">
            <?php if($oketheme['ads_content_middle_act']=='img') {
                if($oketheme['ads_content_middle_url']) { echo '<a href="'.$oketheme['ads_content_middle_url'].'">';}
                    echo '<img src="'.$oketheme['ads_content_middle_img']['url'].'" alt="'.($oketheme['ads_content_middle_img']['alt']?:'ads content middle').'" width="'.$oketheme['ads_content_middle_img']['width'].'" height="'.$oketheme['ads_content_middle_img']['height'].'">';
                if($oketheme['ads_content_middle_url']) { echo '</a>';}
            } else {
                echo $oketheme['ads_content_middle_script'];
            } ?>
        </div>
    </div>
    <script>
        jQuery(document).ready(function($) {
            var contentDiv = $('#content._home ._col1, #content .archive, .wrap-post._artikel');
            var targetDiv = $('.banner-parallax');
            var childDivs = contentDiv.children(':not(.related-content, script)');
            
            if (childDivs.length >= 4) {
                var middleIndex = Math.floor(childDivs.length / 2);
                targetDiv.insertAfter(childDivs.eq(middleIndex - 1)).css('display', 'flex');
            }
        });
    </script>
    <?php 
});

// Iklan Konten #Bottom: 728px
function ads_content_bot() {
    global $oketheme;
    if(!is_ads_active()) return;
    if(empty($oketheme['ads_content_bottom_act'])) return;?>
    <div class="banner" data-customize-partial-id="iklan" data-helper-title="Iklan Konten #Bawah" data-helper-tab="iklan-banner">
        <?php if($oketheme['ads_content_bottom_act']=='img') {
            if($oketheme['ads_content_bottom_url']) { echo '<a href="'.$oketheme['ads_content_bottom_url'].'">';}
                echo '<img src="'.$oketheme['ads_content_bottom_img']['url'].'" alt="'.($oketheme['ads_content_bottom_img']['alt']?:'ads content bottom').'" width="'.$oketheme['ads_content_bottom_img']['width'].'" height="'.$oketheme['ads_content_bottom_img']['height'].'">';
            if($oketheme['ads_content_bottom_url']) { echo '</a>';}
        } else {
            echo $oketheme['ads_content_bottom_script'];
        } ?>
    </div>
    <?php 
}

// Iklan Sidebar #1: 300px
function ads_sidebar1() {
    global $oketheme;
    if(!is_ads_active()) return;
    if(empty($oketheme['ads_sidebar_first_act'])) return;?>
    <div class="banner" data-customize-partial-id="iklan" data-helper-title="Iklan Sidebar #1" data-helper-tab="iklan-banner">
        <?php if($oketheme['ads_sidebar_first_act']=='img') {
            if($oketheme['ads_sidebar_first_url']) { echo '<a href="'.$oketheme['ads_sidebar_first_url'].'">';}
                echo '<img src="'.$oketheme['ads_sidebar_first_img']['url'].'" alt="'.($oketheme['ads_sidebar_first_img']['alt']?:'ads sidebar #1').'" width="'.$oketheme['ads_sidebar_first_img']['width'].'" height="'.$oketheme['ads_sidebar_first_img']['height'].'">';
            if($oketheme['ads_sidebar_first_url']) { echo '</a>';}
        } else {
            echo $oketheme['ads_sidebar_first_script'];
        } ?>
    </div>
    <?php 
}

// Iklan Sidebar #2: 300px
function ads_sidebar2() {
    global $oketheme;
    if(!is_ads_active()) return;
    if(empty($oketheme['ads_sidebar_second_act'])) return;?>
    <div class="banner" data-customize-partial-id="iklan" data-helper-title="Iklan Sidebar #2" data-helper-tab="iklan-banner">
        <?php if($oketheme['ads_sidebar_second_act']=='img') {
            if($oketheme['ads_sidebar_second_url']) { echo '<a href="'.$oketheme['ads_sidebar_second_url'].'">';}
                echo '<img src="'.$oketheme['ads_sidebar_second_img']['url'].'" alt="'.($oketheme['ads_sidebar_second_img']['alt']?:'ads sidebar #2').'" width="'.$oketheme['ads_sidebar_second_img']['width'].'" height="'.$oketheme['ads_sidebar_second_img']['height'].'">';
            if($oketheme['ads_sidebar_second_url']) { echo '</a>';}
        } else {
            echo $oketheme['ads_sidebar_second_script'];
        } ?>
    </div>
    <?php 
}

// Iklan Floating: 1060x90px
function ads_floating() {
    global $oketheme;
    if(!is_ads_active()) return;
    if(!empty($oketheme['ads_floating_left_act'])) { ?>
        <div class="banner-floating _side _left <?=$oketheme['sticky_header_act']?'_sticky':'';?>" data-customize-partial-id="iklan" data-helper-title="Iklan Floating #Kiri" data-helper-tab="iklan-banner">
            <?php if($oketheme['ads_floating_left_act']=='img') {
                if($oketheme['ads_floating_left_url']) { echo '<a href="'.$oketheme['ads_floating_left_url'].'">';}
                    echo '<img src="'.$oketheme['ads_floating_left_img']['url'].'" alt="'.($oketheme['ads_floating_left_img']['alt']?:'ads floating left').'" width="'.$oketheme['ads_floating_left_img']['width'].'" height="'.$oketheme['ads_floating_left_img']['height'].'">';
                if($oketheme['ads_floating_left_url']) { echo '</a>';}
            } else {
                echo $oketheme['ads_floating_left_script'];
            } ?>
            <span class="_close">&times;</span>
        </div>
    <?php }
    if(!empty($oketheme['ads_floating_right_act'])) { ?>
        <div class="banner-floating _side _right <?=$oketheme['sticky_header_act']?'_sticky':'';?>" data-customize-partial-id="iklan" data-helper-title="Iklan Floating #Kanan" data-helper-tab="iklan-banner">
            <?php if($oketheme['ads_floating_right_act']=='img') {
                if($oketheme['ads_floating_right_url']) { echo '<a href="'.$oketheme['ads_floating_right_url'].'">';}
                    echo '<img src="'.$oketheme['ads_floating_right_img']['url'].'" alt="'.($oketheme['ads_floating_right_img']['alt']?:'ads floating right').'" width="'.$oketheme['ads_floating_right_img']['width'].'" height="'.$oketheme['ads_floating_right_img']['height'].'">';
                if($oketheme['ads_floating_right_url']) { echo '</a>';}
            } else {
                echo $oketheme['ads_floating_right_script'];
            } ?>
            <span class="_close">&times;</span>
        </div>
    <?php }
}
add_action( 'wp_footer', function() {
    global $oketheme;
    if(!is_ads_active()) return;
    if(!empty($oketheme['ads_floating_bottom_act'])) { ?>
        <div class="banner-floating _bottom" data-customize-partial-id="iklan" data-helper-title="Iklan Floating #Bawah" data-helper-tab="iklan-banner" data-helper-position="_center-center">
            <?php if($oketheme['ads_floating_bottom_act']=='img') {
                if($oketheme['ads_floating_bottom_url']) { echo '<a href="'.$oketheme['ads_floating_bottom_url'].'">';}
                    echo '<img src="'.$oketheme['ads_floating_bottom_img']['url'].'" alt="'.($oketheme['ads_floating_bottom_img']['alt']?:'ads floating bottom').'" width="'.$oketheme['ads_floating_bottom_img']['width'].'" height="'.$oketheme['ads_floating_bottom_img']['height'].'">';
                if($oketheme['ads_floating_bottom_url']) { echo '</a>';}
            } else {
                echo $oketheme['ads_floating_bottom_script'];
            } ?>
            <span class="_close">&times; <?php _e('Tutup Iklan','oketheme'); ?></span>
        </div>
    <?php }
});

// Share Button
function shareit() { 
	global $oketheme;
	if ($oketheme ['share_act']) {?>
        <div class="shareit" data-customize-partial-id="umum" data-helper-title="Tombol Bagikan" data-helper-tab="lainnya">
            <!-- Facebook -->
            <a class="bttn" href="http://www.facebook.com/sharer.php?u=<?php the_permalink();?>&amp;t=<?php the_title(); ?>" target="_blank" title="<?php _e('Bagikan ke');?> Facebook">
                <i class="icofont-facebook"></i> <span>Facebook</span>
            </a>
            
            <!-- Twitter -->
            <a class="bttn" href="http://twitter.com/share?url=<?php the_permalink() ?>&text=<?php the_title(); ?>" target="_blank" title="<?php _e('Bagikan ke');?> Twitter">
                <i class="icofont-x"></i> <span>Twitter</span>
            </a>
            
            <!-- Whatsapp -->
            <a class="bttn" href="https://api.whatsapp.com/send?text=<?php the_permalink() ?>" target="_blank" title="<?php _e('Bagikan ke');?> Whatsapp">
                <i class="icofont-brand-whatsapp"></i> <span>Whatsapp</span>
            </a>
            
            <!-- Pinterest -->
            <a class="bttn" href="http://pinterest.com/pin/create/button/?url=<?php the_permalink() ?>&media=<?=img_url(get_post_thumbnail_id());?>&description=<?php the_title(); ?>" class="pin-it-button" count-layout="none" target="_blank" title="<?php _e('Bagikan ke');?> Pinterest">
                <i class="icofont-pinterest"></i> <span>Pinterest</span>
            </a>

            <!-- Threads -->
            <a class="bttn _threads" href="https://www.threads.net/intent/post?text=<?php the_permalink() ?>" target="_blank" rel="noopener noreferrer"<?php the_permalink() ?>&text=<?php the_title(); ?>" target="_blank" title="<?php _e('Bagikan ke');?> Threads">
                <img src="<?php echo get_template_directory_uri() . '/assets/img/threads.svg'; ?>" alt="Threads"> <span>Threads</span>
            </a>
            
        </div>
	<?php }
}

// Social Media
function social_media() { 
    global $oketheme;
    if($oketheme['socmed_act']) {?>
        <div class="socmed flexcon gap-5 align-center" data-customize-partial-id="socmed" data-helper-title="Social Media" data-helper-tab="social-media">
            <?php if ($oketheme['facebook']) { ?>
                <a href="<?=$oketheme['facebook'];?>" target="_blank" title="Facebook">
                    <i class="icofont-facebook"></i>
                </a>
            <?php } if ($oketheme['instagram']) { ?>
                <a href="<?=$oketheme['instagram'];?>" target="_blank" title="Instagram">
                    <i class="icofont-instagram"></i>
                </a>
            <?php } if ($oketheme['threads']) {?>
                <a href="<?=$oketheme['threads'];?>" target="_blank" title="Threads">
                    <img style="filter: invert(1);" width="24" height="24" src="<?php echo get_template_directory_uri() . '/assets/img/threads.svg'; ?>" alt="Threads">
                </a>
            <?php } if ($oketheme['youtube']) {?>
                <a href="<?=$oketheme['youtube'];?>" target="_blank" title="Youtube">
                    <i class="icofont-youtube-play"></i>
                </a>
            <?php } if ($oketheme['twitter']) {?>
                <a href="<?=$oketheme['twitter'];?>" target="_blank" title="Twitter">
                    <i class="icofont-x"></i>
                </a>
            <?php } if ($oketheme['tiktok']) {?>
                <a href="<?=$oketheme['tiktok'];?>" target="_blank" title="Tiktok">
                    <i class="icofont-tiktok"></i>
                </a>
            <?php } if ($oketheme['telegram']) { ?>
                <a href="<?=$oketheme['telegram'];?>" target="_blank" title="Telegram">
                    <i class="icofont-telegram"></i>
                </a>
            <?php } if ($oketheme['pinterest']) { ?>
                <a href="<?=$oketheme['pinterest'];?>" target="_blank" title="Pinterest">
                    <i class="icofont-pinterest"></i>
                </a>
            <?php } ?>
        </div>
    <?php }
}

// Maintenance
function maintenance_mode() {
    global $oketheme;
    if ($oketheme['maintenance_act']) {
        if (!current_user_can('edit_others_posts')) {
            die('
			<div style="max-width:800px;border:1px solid #EEE;padding:20px;position:absolute;top:50%;left:50%;transform: translate(-50%, -50%);">
                <h1 style="margin:0 0 20px;">
                    ' . $oketheme['maintenance_title'] . '
                </h1>
                <div class="wrap-post">
                    ' . $oketheme['maintenance_description'] . '
                </div>
			</div>');
        } else {
            echo '<div class="maintenis flexcon align-center gap-5"><i class="m-icon">error</i> Maintenance Mode</div>';
        }
    }
}